- src/BarrelCalorimeterInterlayers_geo.cpp
- src/CompositeTracker_geo.cpp
- src/GaseousRICH_geo.cpp
- src/HomogeneousCalorimeter_geo.cpp
- src/MRich_geo.cpp
- src/ShashlikCalorimeter_geo.cpp
This is needed to support DD4hep built with `-DDD4HEP_USE_XERCESC=ON`.
> treewide: use explicit getAttrOrDefault<std::string>

- .github/workflows/linux-lcg.yml
There is no difference between ubuntu 20.04 and 22.04 in what concerns LCG. Both use the exact same directories.
> feat: only build-test LCG for ubuntu 20.04

- .github/workflows/linux-eic-shell.yml
- .github/workflows/linux-lcg.yml
In order to limit the number of active or queued workflows, this changes workflows to only run on pull_request and as part of a concurrency group which will cancel in-progress jobs.
> feat: limit workflows with concurrency

- .github/workflows/linux-eic-shell.yml
We drop the fibers and the mrich lens for speed, then store that as an artifact for future use in dawn images.
> fix: concentrate sed drops into build-fast-eic-shell artifact

- templates/epic.xml.jinja2
If the config yaml file (for `jinja`) is
```
features:
pid:
drich:
```
it will use the default `compact/drich.xml`, else if it is
```
features:
pid:
drich: my_custom_drich.xml
```
it will instead use `my_custom_drich.xml`
This will allow us to test several versions of the dRICH geometry, in parallel, for example in optics optimization routines. The general idea on our end is:
1. create a new `drich.xml` compact file, with some variables changed
2. create a config file, which specifies the new compact file
3. render the template (`jinja`)
4. simulate
> dRICH: Parse modified drich xml files

- .gitignore
This is a minor convenience fix.
> .gitignore: only ignore xml files in the repository root, not in compact/

- .github/workflows/generate-weekly-meeting-slides.yml
This may help us keep track of new and stale issues, merged and WIP PRs at our weekly meetings... Or it may not.
> ci: generate slides for Wednesday meetings

- templates/epic.xml.jinja2
We pretty much require setting environment variables already, so this just formalizes this. Based on #23 and discussion therein.
For consistency, ip6 should also install its xml files into `share/ip6/compact` but it doesn't exactly because we used a symlink and would conflict with the existing `compact` directory of the detector repository.
> feat*: remove the need for symlinks by using two variables

- compact/tracker/silicon_barrel.xml
The `silicon_barrel` staves are 4 cm wide in x, so 4000 segments are needed, or at least 12 bits. They are 108.46 cm long in y, so 108460 segments are  needed, or at least 17 bits. This changes the 32 bit allocation for x:y from 16:16 to 12:20.
> fix: `silicon_barrel` readout bits `x:32:-12,y:-20`

- .github/workflows/linux-eic-shell.yml
This replaces the posting of a commit comment with updating a commit status. This status is attached to the pull_request, with a link to the eicweb pipeline.
GitHub actions tokens expire, so we cannot pass them to the triggered pipelines. We will have to figure out a way to pass the success of those pipelines back using a token in those pipelines.
For now we will need to check the pending status by hand and override.
Credit for the idea: @veprbl
> test: post commit status with eicweb pipeline

- compact/definitions.xml
`CentralTrackingRegionP_zmax` was incresed by 13 cm in https://github.com/eic/epic/pull/20. To re-adjust the dRICH z-position, this PR: 
- Reduces `ForwardTOFRegion_length` by 13 cm, for dRICH zmin to be at 195 cm
- Reduces `ForwardPIDRegion_length` by 13 cm, for dRICH zmax to be at 315 cm
The following `diff` of the artifact `constants.out` shows consequences for other detectors:
```diff
182c182
< DRICH_SnoutSlope               =        0.457 = DRICH_rmax0 / DRICH_zmin
---
> DRICH_SnoutSlope               =        0.487 = DRICH_rmax0 / DRICH_zmin
190c190
< DRICH_rmax1                    =      104.135 = DRICH_rmax0 + DRICH_SnoutLength * DRICH_SnoutSlope
---
> DRICH_rmax1                    =      104.744 = DRICH_rmax0 + DRICH_SnoutLength * DRICH_SnoutSlope
192,193c192,193
< DRICH_rmin0 …
```
> fix (dRICH): correct z-position after recent tracker updates

- src/DRICH_geo.cpp
Swap the construction of mirrors and sensors in `epic/src/dRICH_geo.cpp`. The sensors must be added last, since a call to `CherenkovDetector::CreatePhotonDetectorInstance` will internally add the sensor surface itself to the list of optical boundaries a typical photon will encounter. So the list of boundaries must be in this order:
- vessel entrance
- aerogel entrance
- aerogel exit
- filter entrance
- filter exit
- mirror
- sensor
The way we had it before, mirror and sensor boundaries were switched, and `IRT::Transport` was therefore never seeing the mirror boundary
The variables `sensorCentroidX,Y` and `sensorCount` can no longer be used (without some mild refactoring), and currently aren't being used anyway. They have been commented out, but remain in the code in case we want them for …
> fix (dRICH): swap mirror and sensor construction order

- src/BarrelTrackerWithFrame_geo.cpp
Saying that the triangular structure of silicon staves are made of carbon fiber layer of thickness d. Given the triangle's outer height h, width w,  the inner height of the triangle should be the h - d - d/cos(theta) instead of h - d - d/tan(theta),  where tan(theta)=h/(w/2).
> Bugfix: Tracker bar triangular CarbonFiber frame thickness

- compact/drich.xml
```
```
Wide, collimated photon beams reflecting off the mirror, to show the parallel-to-point foci
8 GeV pions, thrown at 4 different polar angles within the dRICH acceptance. Note the highest-theta has no aerogel ring, because there is no aerogel coverage at high theta.
Thrown 8 GeV pions, equally distributed in theta and phi, to one dRICH sector. The lowest theta pions are thrown at phi=0 only; the higher thetas have 5 phi bins: one along phi=0, one along each sector boundary (adjacent sector hit maps are below), and one in between phi=0 and the sector boundary.
We have losses at high theta along the sector boundary (note the missing gas rings)
> fix(dRICH): improve optics

- compact/drich.xml
Updated pixel hit maps (cf. #24 for previous hit maps):
> fix(dRICH): add sensor coverage for high theta along sector boundaries

- .github/workflows/linux-eic-shell.yml
- compact/unused/tracking_config_mgpds.xml
There are some ill-formed xml files that are not caught in the `compact/` tree. That is because we are currently only checking `compact/*.xml` and files are at a deeper level.
> ci: use recursive xmllint

- compact/tracker.xml
- compact/tracker/silicon_barrel.xml
- compact/tracker/silicon_disks.xml
- compact/tracker/support_service_assembly.xml
- compact/tracker/vertex_barrel.xml
Vertex barrel: removed support cylinder outside the 2nd vertex layer, and connect vertex layers to cone with disks.
Silicon disks: adjusted z positions, and make the backward design symmetric to forward region. 5 disks on each side.
> updated silicon tracker geometry to LBL design with symmetric disks

- compact/optical_materials.xml
- src/DRICH_geo.cpp
The dRICH sensitive detector now uses `Geant4OpticalTrackingAction` (see https://github.com/AIDASoft/DD4hep/pull/967 and https://eicweb.phy.anl.gov/EIC/NPDet/-/merge_requests/270/). This PR removes `RINDEX` tables from the RICH sensor surfaces, as it's not clear where they came from and they weren't needed in the ATHENA proposal (which effectively also used `Geant4OpticalTrackerAction`).
@alexander-kiselev @chchatte92 @ajitkmaurya 
With these changes, we go from about 60 raw dRICH hits to almost 300, for a 40 GeV pion.
No
Not beyond the dRICH
> fix(dRICH): remove `RINDEX` tables from dRICH sensor optical surfaces

- .github/workflows/generate-weekly-meeting-slides.yml
This adds a `since` input to the meeting slides run to allow for deviations from the default '1 week ago' durations. Also changes the scheduled run time to Monday 16:30 UTC, 12:30 EDT.
> ci: add 'since' input; scheduled run Monday 16:30Z

- .github/workflows/linux-eic-shell.yml
- .github/workflows/linux-lcg.yml
The update from github-action-cvmfs@v2 to v3 adds caching of the apt downloads to speed up recurrent cvmfs installations. This should make the setup of individual jobs a bit faster, but in particular it should hit the CERN servers less hard for each job.
> ci: from github-action-cvmfs@v2 to v3 with apt caching

- src/FileLoader.cpp
As of DD4hep-1.22, https://github.com/AIDASoft/DD4hep/pull/936, any plugin returning a zero return value is assumed to have failed. This is somewhat counter-intuitive for plugins that simply return a long status code, but it is inteded to allow recursive calls and is in line with what other plugins already do, e.g. `return field` or `return sdet`.
> fix: non-zero return for plugin success as of dd4hep-1.22

- .github/workflows/linux-eic-shell.yml
- .github/workflows/linux-lcg.yml
While the compatibility setting to install also under the name of ECCE is still ON, this has worked, but we should move towards just using `epic.xml` and associated files.
> ci: use epic.xml instead of ecce.xml

- .github/workflows/linux-eic-shell.yml
This adds default values to the `workflow_dispatch` inputs which are then used with `push` or `pull_request` events. We need `workflow_dispatch` primarily to start pipelines from the `ip6` repository.
> ci: workflow_dispatch with inputs

- .github/workflows/linux-eic-shell.yml
This allows for forwarding status reporting callback location to external pipelines triggered by this repository.
In particular, a pull request in eic/ip6 could now trigger eic/epic, and eicweb/detector_benchmarks, eicweb/reconstruction_benchmarks, and eicweb/physics_benchmarks. The reports from the eicweb benchmarks will be reported back to the original ip6 pull request.
(Yes, all of this is still easier than moving ip6 into epic right now.)
No.
No.
> ci: allow repository+sha worklow_dispatch inputs

- .github/workflows/auto-update.yml
We can set pull requests to automatically squash merge, but we can NOT set it to automatically rebase when the base branch receives a push.
A new automatic workflow triggered by pushes to the main branch that updates outstanding pull requests which are set to auto-merge.
No changes to geometry code.
This may introduce automatic pull request updates, which will require users to know how to deal with git pulls after a remote branch has been rebased and force pushed. However, this is aimed at branches that are set to auto-merge and therefore intended to have completed development. The use case where this may be an issue is for trivial changes where auto-merge is selected before first checks complete, those checks then fail, a push to main triggers and auto-update, and the user want to fix …
> ci: auto-update pull requests

- CMakeLists.txt
- README.md
Ideally, there would have been a warning message for users living with EPIC_ECCE_LEGACY_COMPAT=ON. But since many are only now learning things through the tutorials it makes sense to drop ECCE ASAP and reduce the confusion.
A small follow up to yesterday's tutorial session. This removes unnecessary symlinks for users that are now just learning things.
No.
Supposedly, yes.
> cmake: use EPIC_ECCE_LEGACY_COMPAT=OFF

- src/SupportServiceMaterial_geo.cpp
This removes debugging output that has been showing up on every geometry load.
No
Yes, removes output that was shown before, i.e.
```console
(0,0,13.6753)
(0,0,-0.0751)
(0,0,0.0999)
(0,0,-13.6753)
(0,0,-0.1001)
(0,0,0.0749)
(0,0,173.3)
(0,0,-0.2)
(0,0,0.1)
```
> fix: remove SupportServiceMaterial debug output

- CMakeLists.txt
- compact/drich.xml
- src/DRICH_geo.cpp
- removes optional dependence on `IRT` (auxfile creation is [moved to `drich_dev`](https://github.com/eic/drich-dev/pull/32) until integration of `IRT` with `EICrecon` or `algorithms`)
- adds `Constant`s with the unique name prefix `DRICH_RECON_`, which will be used in the reconstruction, since some geometry parameters are otherwise difficult to access from the `Detector` handle (e.g. the mirror centers)
- some `Constant`s are redundant, but we want it to be clear that any `DRICH_RECON_` `Constant` is required for the reconstruction algorithm; thus any changes to these constants' values may need to be accounted for on the reconstructed side (hopefully only major changes)
Only in the IRT reconstruction, which is undergoing refactoring. The IRT geometry creation code is moved to …
> feat(dRICH): remove IRT `auxfile` and add constants to facilitate geometry access from reconstruction

- compact/tracker/mpgd_barrel.xml
This addresses the small overlaps between staves that have been bugging the geant4 overlap checks. We were calculating the width of perfectly-circle-filling staves by using the radius of the center of the middle of the module, but then we were placing them starting at an envelope rmin which was half a thickness smaller. This caused overlaps at the inner corners for both inner and outer MPGD layers.
This change should make the staves a tad bit smaller (ratio of thickness over radius of placement), cause a slightly smaller efficiency, but should improve the pipeline stabilities by not triggering overlaps in the MPGDs.
@mposik1983 I trust this is ok at least as a stopgap while better solutions are developed.
No.
Slightly narrower MPGD staves.
> fix: calculate MGPD stave width based on envelope rmin, not mid-module rmin

- .github/workflows/linux-eic-shell.yml
In the past (ATHENA, ECCE) we were running benchmarks for multiple configurations. This brings back that functionality for EPIC on GitHub. At this point, the matrix is just epic_sciglass and epic_imaging, as the likely two configurations in the October 2022 campaign.
No.
Multiple detector configurations will be tested by default, including barrel imaging calorimeter, which has not been included in tests for a while.
> feat: run epic_sciglass and _imaging benchmarks

- CMakeLists.txt
- compact/tracker/central_tracker_hybrid_v2.xml
- compact/tracker/mpgd_barrel.xml
- compact/tracker/silicon_barrel.xml
- compact/tracker/silicon_disks.xml
We currently write to a separate Hits collection for each barrel and endcap tracker detector definition. This is required by some of the dependencies because the collections are not read correctly if we don't do this.
This branch moves everything back into a single collection to debug the underlying issues and figure out where they exactly are coming from.
About half a year ago (or longer), when switching fully from dd4pod to edm4hep, we had to put all hits in a dedicated collection instead of reusing the collections across subdetectors. This reverts the behavior as DD4hep versions 1.21 and later have fixed this issues.
- Benchmarks need updating:
Yes. This now requires DD4hep 1.21 or newer for correct behavior (more recent than LCG 101).
Yes. By default the hits collections for vertex …
> fix: revert to a single Hits collection for tracker

- compact/drich.xml
- compact/optical_materials.xml
- src/DRICH_geo.cpp
Document how to generate material property tables for the dRICH and pfRICH.
Close #105 
Alternatively, we could consider moving this generation code here to `epic`. Another possibility is removing these XML tables and use the material property table generation code directly as a plugin here, but I think for that we would need to be able to convert a `G4Material` to a `TGeoMaterial` (the reverse is done when converting `TGeo`->`Geant4`). Anyway, better documentation is a start in the right direction.
This also makes the change `dRICh` -> `dRICH` everywhere; despite attempts from some to call it "dRICh", it seems "dRICH" is much more popular...
No
No
> doc(dRICH): generation of dRICH and pfRICH material property tables 

- compact/ecal_barrel_interlayers.xml
- compact/materials.xml
This PR adjusts the material of the SciFi/Pb matrix by including glue with properties like in: Z. Papandreou. BCAL Calorimetry Response. Technical report, GlueX Collaboration, 2007. [GlueX-doc-840-v2](https://halldweb.jlab.org/doc-public/DocDB/ShowDocument?docid=840). The mixture of Pb and Glue is implemented as radiator, and SciFi material has been also adjusted to match better the GlueX one as described in the cited note.
no
no
> Add SciFi/Pb materials

- compact/definitions.xml
- compact/ecal_barrel.xml
- compact/ecal_barrel_interlayers.xml
- compact/hcal/hcal_backward.xml
- compact/hcal/hcal_barrel.xml
- compact/hcal/hcal_forward.xml
- compact/unused/ecal_barrel_hybrid.xml
Change number of staves to 24
Add z-segmentation for fibers
Geometry and readout update for the imaging barrel calorimeter.
Resolve issue #119 
This PR requires the implementation of waveform signals in the digitization step for the hits separation in fibers.
No
> Imaging Barrel Calorimeter Geometry and Readout Update

- .github/workflows/auto-update.yml
Using a standard GitHub workflow token for the pull request auto-updates does not allow resubmitting the workflows after the updates. This is annoying since it prevents auto-merges from actually merging. This replaces the use of a standard token with a personal access token that has these permissions.
No.
No.
> ci: use a dedicated PAT for auto-update resubmit

- .github/workflows/linux-eic-shell.yml
- compact/solenoid.xml
- compact/tracker.xml
- src/FieldMapBrBz.cpp
- src/FileLoaderHelper.h
Instead of downloading artifacts, we should use the cached versions. This ensures that is the case for
- magnetic field maps,
- tracking material maps,
- any other potential large artifacts.
No.
No.
> Ensure magnetic fields and other artifacts are retrieved from cache

- src/EndcapTOF_geo.cpp
This PR fixed an overlap in the endcap TOF disk that was not seen with checkOverlaps, but with checkOverlaps.py. This is also related to PR #191 
No.
No.
> TOF disk overlap fix for PR 191

- compact/definitions.xml
Add B0ECal system id to definitions
No.
No.
> Hotfix: Add B0ECal system id to definitions

- compact/definitions.xml
The solenoid is now slightly longer (5 cm) and shifted to the backward region by -10 cm, according to https://eic.jlab.org/Geometry/Detector/Detector-20220929172703.html. The magnetic field remains unchanged.
No.
Yes, slightly different solenoid material locations.
> feat: update solenoid offset and length

- src/BarrelTrackerWithFrame_geo.cpp
- src/MPGDDIRC_geo.cpp
- src/TrapEndcapTracker_geo.cpp
```output
src/MPGDDIRC_geo.cpp:126:52: error: cannot pass object of non-trivial type 'std::__1::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
printout(DEBUG, "MPGDDIRC_geo", "gas: %f", comp_name);
^
```
> MPGDDIRC: fix compilation error and some format strings

- compact/definitions.xml
The PR switches the 5 hit IDs (163 - 167) used the FoCal ZDC back to the 2 IDs used (163-164) for the old ATHENA ZDC. This is because the digitization is problematic for the FoCal design at the moment.
It should not - it should AVOID a breaking issue at digitization.
It should make the default behavior work properly.
> Updated ZDC ids to point to older ZDC ATHENA geometry for this campaign.

- templates/epic.xml.jinja2
Fixes an issue introduced in https://github.com/eic/epic/pull/186
The current logic enables farforward whenever `'farforward' not in features` which makes it harder to disable farforward.
> epic.xml.jinja2: fix logic for farforward

- compact/ecal_barrel_sciglass.xml
- templates/epic.xml.jinja2
The DIRC and Ecal barrel sciglass envelope volume were overlapping about 2 cm at the DIRC readout box. This change from -1.9 to -1.87 does not introduce overlaps in the sciglass and removes overlaps between the DIRC and the sciglass. With an MCP height of 23.746 cm starting at 70 cm radius, the DIRC is well within the 100 cm outer radius, so I think modifying the sciglass is the right approach here.
No.
No.
> fix: decrease negative eta of cutout sciglass envelope

- src/HomogeneousCalorimeter_geo.cpp
HomogeneousCalorimeter_geo.cpp had some `cout` statements that were replaced by printout statements to the DEBUG stream. This keeps the terminal output clean and organized.
No.
No.
> fix: remove spurious debugging output

- .github/workflows/linux-eic-shell.yml
No need for eicweb pipelines for imaging and sciglass.
No.
No.
> fix(ci): only trigger eicweb for arches, brycecanyon

- compact/drich.xml
This should stop transient dRICH overlaps, since there are likely still small overlaps that are not being detected by overlap checks at the default tolerance (0.1 mm).
no
no
> fix(dRICH): increase gap between sensors

- templates/epic.xml.jinja2
Restore the tracker in `epic.xml`, which is generated by default from the template.
No.
No.
> hotfix: restore tracker in default epic.xml

- compact/definitions.xml
- compact/hcal/hcal_forward_insert.xml
- src/InsertCalorimeter_geo.cpp
Updated the forward insert's hole initial/final radius and x-position after the z positions of the forward endcap were changed to managerie values (329.6 cm for ECal, 359.6 for HCal).
Fixed bug where the attribute backplate_thickness wasn't being read in.
None
Adjusts default shape of the forward inserts
> Update insert hole parameters, fix backplate attribute bug

- .github/workflows/linux-eic-shell.yml
With the merge of the barrel hcal, we have temprorarily failing overlap checks due to (it appears) a bug in the underlying classes. While this is being solved, we want to continue having a working CI system, so we disable the barrel hcal from some jobs. This PR moves stuff around so at least the eicweb benchmarks pipelines are started again (even if they may fail).
No.
No.
> fix: split overlap check jobs for barrel hcal

- compact/hcal/barrel_gdml.xml
Simplified description of tile solid shapes for outer HCAL
No breaking changes found/expected
The tile shapes have been reduced to about 10% of their original complexity.  Most of the complexity in terms of the facets describing the tiles was associated with small mounting holes in the tiles SiPM mount/light blocker. This is unnecessary for the description of the tiles in simulations and adds much more complexity, which increases the time required for G4 to decide where it is in a solid.  This should result in a reduced time in traversing the oHCAL geometry and simplify things like the overlap checks. 
Unfortunately, this does not affect at all the spurious overlap errors reported in G4 between disparate objects that are clearly not overlapping and nowhere near to each other.  In …
> Simplified tile shapes for outer HCAL

- src/SciGlassCalorimeter_geo.cpp
The full "z" length includes only a single "non_overlap_length".
No
Yes
> BUGFIX: SciGlassCalorimeter: fix cutout margins

- compact/tracking/support_service_assembly.xml
Minor update on the silicon tracker service cable thickness along the cone in terms of uniformly distributed effective aluminum. 
For simplicity, use the same value for P and N directions.
> update the silicon tracker service cable thickness along the cone

- compact/ecal/barrel_sciglass.xml
- configurations/sciglass_only.yml
- src/SciGlassCalorimeter_geo.cpp
Replaces a single 3 mm wall with two 3 mm walls separated by a 6 mm Air Gap
No
Yes
> SciGlassCalorimeter_geo: implement double walls for wedge box and 6 mm gap

- compact/definitions.xml
IP6 merged a hard-coded ID number into master, which needed to be replaced by a defined ID number and added here.
No.
No.
> hotfix: synchronize IP6 ID numbers again

- compact/hcal/backward.xml
Signed-off-by: lkosarz <leszek.kosarzewski@gmail.com>
Fixes segmentation issue due to polyhedra corners sticking out of rmax.
No.
No.
> Fix issue #277 - error due to hits hitting nHCal corners

- compact/materials.xml
Until now we were relying on a local [patch](https://github.com/eic/eic-spack/blob/v0.18/packages/geant4/birks.patch) to geant4 to define Birks constants. That's error-prone and makes the geometry dependent on external patches in a non-obvious way. This introduces the Birks constants for those materials that are used in our geometry, set to the values in the patch that has been in use:
- PbWO4: 0.0333*mm/MeV
- PlasticScint: 0.126*mm/MeV
- Polystyrene: 0.126*mm/MeV 
- SciGlass: 0.0333*mm/MeV
No.
No.
> fix: define Birks constants in materials definition

- src/EndcapTOF_geo.cpp
It appears, that the wrong coordinate system was used for the TOF ACTS implementation. One needs to use "xzy" instead of "zyx". 
With this change, no more surface errors appear and the endcap hits are available.
```
[2022-11-11 11:02:35.749] [tof_efficiency] [trace] TOF barrel hits:
[2022-11-11 11:02:35.749] [tof_efficiency] [trace]           [x]        [y]        [z]     [time]
[2022-11-11 11:02:35.750] [tof_efficiency] [trace] TOF endcap hits:
[2022-11-11 11:02:35.750] [tof_efficiency] [trace]           [x]        [y]        [z]     [time]
[2022-11-11 11:02:35.750] [tof_efficiency] [trace]        523.00     -95.19    1914.95     6.6580
[2022-11-11 11:02:35.750] [tof_efficiency] [trace] Going over tracks:
[2022-11-11 11:02:35.750] [tof_efficiency] [trace]           [x]        [y] …
```
> fix for endcap TOF coordinate conversion

- src/BarrelCalorimeterSciGlass_geo.cpp
This places towers inside a sector volume instead of placing them directly in the envelope.
> SciGlassCalorimeter: place towers in a sector volume

- .github/workflows/generate-weekly-meeting-slides.yml
- compact/ecal/backward_PbWO4.xml
- compact/ecal/barrel_sciglass.xml
- compact/ecal/forward_homogeneous.xml
- compact/ecal/forward_insert_homogeneous.xml
- compact/materials.xml
- compact/optical_materials.xml
- configurations/bhcal.yml
- src/BarrelCalorimeterSciGlass_geo.cpp
- src/BarrelHCalCalorimeter_geo.cpp
- src/EndcapTOF_geo.cpp
- src/HomogeneousCalorimeter_geo.cpp
- src/InsertCalorimeter_geo.cpp
- src/MPGDDIRC_geo.cpp
- src/SciGlassCalorimeter_geo.cpp
Cherry-pick of f06a7d8 and 9dfcdb0 into 22.11 to reduce memory use.
- @veprbl: do we expect any actual changes due to f06a7d8 and 9dfcdb0 ?
No.
No.
> Sciglass backport to 22.11

- .github/workflows/linux-eic-shell.yml
- compact/pid/drich.xml
- compact/pid/pfrich.xml
- src/DRICH_geo.cpp
- src/PFRICH_geo.cpp
- Remove redundant extra `*RICH_RECON_*` constants
- All `*RICH_` constants to snake case
yes, but only to downstream code, namely `eicrecon` and `drich-dev`
no
> feat!: remove redundant `*RICH_RECON` constants

- doc/sciglass_tower_front_view.svg
- src/BarrelCalorimeterSciGlass_geo.cpp
Allow specifying azimuthal flaring angle for towers using a new `flare_angle_azimuthal` parameter.
This parameter is not used in the current engineering geometry, and is implicitly calculated for it assuming a truncated pyramid tower shape. For AI/ML optimizations we need to relax this constraint.
No
No
> BarrelCalorimeterSciGlass: allow specifying azimuthal flaring angle for towers

- compact/far_forward/roman_pots_eRD24_design.xml
This changes the location of portions of the Roman Pots planes to make them "high acceptance". It should be noted that it is obvious (now) that the arrangement of the planes needs to be re-shuffled in the next campaign to optimized the 10 sigma distance. Additionally, need to add functionality to adjust the 10sigma position at run-time. Will do later with a different PR.
This PR makes a minimal change to the compact file, and only adjusts some constants for the placement of the detector planes.
No.
Yes, it will increase the overall acceptance of far-forward protons at low-Pt (in the Roman Pots, nowhere else).
> Uncomment settings for high-acceptance, comment out high-divergence.

- .github/workflows/linux-lcg.yml
- CMakeLists.txt
DD4hep 1.21 is required for its VariantParameter support. This enforces this at the cmake stage, rather than failing compilation later on. Because LCG_101 does not container DD4hep 1.21, the LCG workflow is disabled.
No.
No.
> fix: require DD4hep 1.21 in CMakeLists.txt

- .github/workflows/linux-eic-shell.yml
- compact/ecal/barrel_interlayers.xml
- src/BarrelCalorimeterInterlayers_geo.cpp
This PR implements the cladding of the Sci Fibers in the SciFi/Pb barrel Calorimeter. Now the fibers are implemented in assemblies of fiber cores (sensitive) and cladding (insensitive) and placed inside the lead slice. This resulted in the fastest geometry implementation I could achieve (no significant change wrt the previous implementation).
No
No
> Add cladding to fibers

- compact/ecal/barrel_sciglass.xml
A design update. Towers at mid-rapidity will now be shorter:
No
Yes
> barrel_sciglass.xml: shorten family 1 and 2 towers to 40 cm

- .github/workflows/linux-eic-shell.yml
- CMakeLists.txt
- src/B0Tracker_geo.cpp
- src/BarrelTrackerWithFrame_geo.cpp
- src/FileLoaderHelper.h
- src/TrapEndcapTracker_geo.cpp
As of version 1.24, DD4hep exports `-Wno-psabi` in its compiler flags to suppress gcc ABI warnings in the DD4hep header Shapes.h. This PR has us pick up these upstream compiler flags to pick this up. This means:
`-Wshadow -Wformat-security -Wno-long-long -Wdeprecated -fdiagnostics-color=auto -Wall -Wextra -pedantic -Wno-psabi`
No.
No.
> fix: set dd4hep compiler flags to suppress ABI warnings on arm

- scripts/subdetector_tests/draw_bemc_scfi_grids.py
- src/BarrelCalorimeterInterlayers_geo.cpp
It adds geometry for grids so we can retrieve the position/dimension of a grid during the digitization/reconstruction.
No, it updates the internal behavior of geometry construction for the BarrelCalorimeterInterlayers. It does not change any of the interfaces to use it.
No.
> Implement geometry volumes for fiber grids in BEMC ScFi

- compact/definitions.xml
Due to limitations in DD4hep we were using symmetric limits here, but DD4hep 1.24 allows asymmetric regions. This defines the "tracker region" which is the region where created secondaries will be stored in the MCParticles collection. This setting is backwards compatible in that `tracker_region_zmax` will be used as the symmetric limit for older DD4hep versions.
No.
No.
> feat: use asymmetry tracker region in secondary particle handler

- compact/far_backward/definitions.xml
- compact/far_backward/lumi.xml
Activate the direct lumi photon CAL to the main lumi.xml and relocate it further backward, behind spectrometer CAL.
> Add direct lumi CAL to lumi.xml and relocate it further backward.

- compact/definitions.xml
- templates/epic.xml.jinja2
By defining our own world volume, we gain some flexibility in defining differently shaped world volumes, e.g. a central detector hall with far forward and far backward tunnels. It also may allow us to treat the world as a geant4 region with association user limit setters.
@c-dilks This has required moving the `optical_materials.xml` inclusion outside the `<includes>` tag. When the file is included inside the `<includes>` tag, it requires that the world is created at that time since it is treated as a new translation unit. When the file is included with a simple `<include>` tag, it includes the contents in-place in the current translation unit. Can you please double-check that the change to the optical_materials include line does not affect optical properties, in particular your optical …
> feat: explicitly define a world volume and material

- .github/workflows/linux-eic-shell.yml
The gitlab trigger-geoviewer job reports as epic_arches, but the CI system here was waiting for arches.
No
No
> ci: expect trigger-geoviewer with name it will be reported

- compact/ecal/forward_insert_homogeneous.xml
This reduces the readout size of the ECal insert from 2x2 cm to 1x1 cm.
None.
No, just changes the readout size of the ECal insert.
> Change ECal insert's readout to 1x1 cm from 2x2 cm

- src/BarrelCalorimeterSciGlass_geo.cpp
Double walls were implemented in
3baa9d32 ('SciGlassCalorimeter_geo: implement double walls for wedge box and 6 mm gap')
so comments about missing wall thickness are outdated since then. This commit removes them.
No
No
> SciGlassCalorimeter_geo: remove outdated comments

- compact/pid/drich.xml
- src/DRICH_geo.cpp
Add a new "debugging" mode for the dRICH to draw only one sector (makes event displays easier to see).
no
no
> feat(dRICH): add test setting `DRICH_debug_sector` to draw only one sector

- compact/pid/drich.xml
- Update sensor sphere center following guidance from Luca and Marco; the radius remains fixed at 110 cm
- Set mirror focus tune z such that the mirror radius = 2x the sensor sphere radius
- Adjust mirror focus tune x to re-center the focal region on the sensors
- Disable the azimuthal limits of the sensor sphere (so more sensors than necessary will be placed); it is clear the true azimuthal limits of where the rings will appear are not quite aligned with these azimuthal cuts; we will re-think this later when implementing "sensor window boxes", where all the sensors will be contained in a `Box` filled with `AirOptical` (one per sector)
no
no
---
```
DRICH_mirror_radius       =      221.310
DRICH_mirror_center_x     =      118.878
DRICH_mirror_center_y     =        0.000 …
```
> dRICH: update sensor sphere positioning and re-focus

- compact/optical_materials.xml
Fixes #202, warning due to aerogel components not summing up to 1. The fraction of carbon is almost certainly not 10%, and instead more likely 0.1%. In fun4all, there was 0 carbon. Ignoring the arbitrary separation into two components of Si02. Also ignoring the 10x higher density than [in fun4all](https://github.com/eic/fun4all_coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Reco.cc#L1360). @msar15 
No.
No.
> fix: mRICH aerogel sum components to 1

- src/DRICH_geo.cpp
Add constant `DRICH_num_sensors` to provide easy access to the number of SiPM sensors per sector. Warn if this number is different in any sectors.
no
no
> feat(dRICH): add a constant to provide the number of sensors

- compact/far_forward/roman_pots_eRD24_design.xml
XML is oddly specific about not having `--` inside a comment, so when a comment tag `` is not closed properly and falls through to the next comment end tag, it has an illegal `--` inside the comment.
"For compatibility, the string " -- " (double-hyphen) must not occur within comments." [https://www.w3.org/TR/REC-xml/#sec-comments]
(Git branch names, on the other hands, are more forgiving.)
No.
No.
> fix: bad comment bad

- compact/pid/drich.xml
Adjust `sphericalpatch` cuts, which define the limits of the sensor sphere.
Previous limits:
```
rmin = "DRICH_rmax1 + 3.0*cm" = 107.656 cm
rmax = "DRICH_rmax2 - 3.0*cm" = 182.000 cm
```
New limits from Luca:
```
rmin = 110 cm, but actually needs to be 111 cm to remove extra "dangling" sensors at low theta
rmax = 179 cm
```
no
no, but slight change in polar acceptance boundary
> fix(dRICH): adjust sensor region boundaries

- compact/definitions.xml
- compact/display.xml
- compact/display_detailed.xml
- compact/display_geoviewer.xml
- compact/ecal/barrel_interlayers.xml
- scripts/subdetector_tests/draw_bemc_scfi_grids.py
- src/BarrelCalorimeterInterlayers_geo.cpp
Update the geometry for barrel ecal:
Change geometry to 48 staves
Change the readout grid to cover even distance in Delta Phi (see the picture below) - i.e., always divide stave (1/48) into 5 readout grids in one readout layer
Add 3 cm of Aluminum at the back of the calo
No
No
> Update Geometry for Barrel EMCal

- scripts/subdetector_tests/draw_bemc_scfi_grids.py
This PR fixes a bug in the SciFi/Pb plotting script. After https://github.com/eic/epic/commit/8d2c50081146390402f4d7178d98b196dcb207d7 the daughter of the grid is `fiber` only, not `fiber_core`. Because of this issue fibers were not plotted correctly. 
- [#] Bug fix (issue #__)
no
no
> fix grid plotting script for SciFi/Pb

- templates/epic.xml.jinja2
Recent DD4hep supports defining a world limit set and region, which extends to the full simulation. This doesn't introduce any limits, but demonstrates how to do it. This can also be extended to individual detectors.
No.
No.
> feat: define example world limit set and region

- compact/display.xml
- compact/far_forward/ZDC_Ecal_WSciFi.xml
- compact/far_forward/ZDC_Hcal.xml
Badly named visualization parameters in the ZDCEcal, drich and barrel_sciglass prevented JSRoot from correctly visualizing a number of detectors (for me) including B0 tracker, Roman Pots, LowQ2 tagger
No
No
> visualisation attributes given correct names to allow JSROOT to show detector properly

- CMakeLists.txt
If CMAKE_INSTALL_PREFIX is not defined, then it takes on an incorrect default value that is written into the `setup.sh` script (which leads to a `setup.sh` installed by default in the source dir with a DETECTOR_PATH set to a /usr/local dir).
This commit explicitly defines the CMAKE_INSTALL_PREFIX to the source directory if it is not explicitly set.
No.
No.
> fix: set default CMAKE_INSTALL_PREFIX

- compact/ecal/forward_insert_homogeneous.xml
As mentioned in Issue #440, this changes the ECal insert readout size to 1.25 cm x 1.25 cm from 1 cm x 1 cm.
None that I know of.
Changes default readout size of ECal insert.
> Change ECal insert readout size to 1.25 cm x 1.25 cm

- compact/materials.xml
- compact/optical_materials.xml
- compact/pid/dirc.xml
The hpDIRC is very inefficient right, causing 20x slowdowns for DIS datasets. Since there is no reconstruction yet for the hpDIRC, there is no reason to simulate all these photons.
This PR reverts the optical materials to their regular counterparts.
@niwgit This follows in part from today's discussion. There is no digitization or reconstruction of the hpDIRC, so in the short term there is no real use for these optical photons. Before re-enabling the optical photons by default we would probably need digitization and reconstruction, and we need a better understanding of the impact on running times.
Cc: @mdiefent @rahmans1 @T-Britton 
- We need a benchmark to catch regressions in running time like this... @veprbl @torrijeske 
Yes, reverts to not having optical photons in the hpDIRC.
Yes, no …
> fix: disable optical photon generation in hpDIRC

- compact/tracking/silicon_barrel.xml
- compact/tracking/silicon_disks.xml
- compact/tracking/vertex_barrel.xml
Updated the segmentation of the silicon tracking detectors from a 10x10um to 20x20um granularity. This reflects the most up-to-date expectations of the pixel size from the tracking working group.
> Si tracker granularity

- compact/tracking/definitions.xml
- compact/tracking/definitions_arches.xml
- configurations/arches.yml
- configurations/arches_mrich_gdml.yml
- configurations/brycecanyon.yml
- configurations/brycecanyon_no_pfrich.yml
- configurations/brycecanyon_pfrich_gdml.yml
- configurations/full.yml
- configurations/imaging.yml
The default epic.xml geometry, constructed from the full.yml configuration, is updated to use the pfRICH and imaging barrel calorimeter.
No.
Yes, different detector is default.
> feat: epic full with pfrich, imaging

- compact/far_forward/roman_pots_eRD24_design.xml
This removes two duplicated constants which are throwing warnings in the loading of geometry.
Also removed tabs in favor of spaces for alignment.
No.
No.
> fix: remove duplicate constants in roman_pots_eRD24_design.xml

- compact/ecal/barrel_interlayers.xml
Reduced the number of sublayers in Barrel ECAL from 15 to 12
to
Overall shrinking of the barrel
to
No
Shortens Barrel Calorimeter size
> EcalBarrelScFi: reduce EcalBarrel_TotalFiberLayers_num from 15 to 12

- compact/definitions.xml
From the discussion in the calorimeter meeting (see [here](https://indico.bnl.gov/event/19514/contributions/76474/attachments/47553/80622/main.pdf)), the pECal only needs to cover up to eta = 1.4.
No breaking changes. Users do not need to update their code.
No.
> Change pECal radius to cover up to eta = 1.4

- CMakeLists.txt
- src/FieldMapBrBz.cpp
In the next DD4hep version, the field type will be stored in a variable `field_type` not `type`. This will cause epic to fail to compile. Of course, until then this version will fail to compile. And all older geometries will fail to compile with the newer DD4hep as well. So that's kinda annoying and something I don't have a good solution to...
No.
No.
> fix: dd4hep::CartesianField renamed type to field_type

- compact/ecal/forward_insert_homogeneous.xml
Matches the Ecal insert readout with the surrounding Ecal readout size (24.925 mm x 24.65 mm, about 2.5 cm x 2.5 cm).
None.
Changes the default size of the Ecal insert readout.
> EcalEndcapPInsert: Change Ecal insert readout to 2.5 cm x 2.5 cm

- compact/ecal/barrel_interlayers.xml
This #PR implements changes in the Imaging lBarrel ECAL geometry. We currently have 6 slots for AstroPix layers and slots 1-3-5-6 are filled with the sensitive layers. Other slots have only air inside. 
no (but the topo cluster reconstruction efficiency will be affected)
yes
> Implement 6 AstroPix slots with sensitive layers 1-3-5-6

- compact/definitions.xml
- compact/pid/pfrich.xml
See Elke's slides: https://indico.bnl.gov/event/19808/
Decreases z-min of the pfRICH by 5 cm to accommodate 2 new MPGD disks.
No impact on other detector constants (except for tracker support).
```diff
148c148
< BackwardEndcapSupportCyl_length =       49.100 = BackwardEndcapSupportCyl_zmax-BackwardEndcapSupportCyl_zmin
---
> BackwardEndcapSupportCyl_length =       44.100 = BackwardEndcapSupportCyl_zmax-BackwardEndcapSupportCyl_zmin
150c150
< BackwardEndcapSupportCyl_z     =      148.150 = 0.5*(BackwardEndcapSupportCyl_zmin+BackwardEndcapSupportCyl_zmax)
---
> BackwardEndcapSupportCyl_z     =      150.650 = 0.5*(BackwardEndcapSupportCyl_zmin+BackwardEndcapSupportCyl_zmax)
152,154c152,154
< BackwardEndcapSupportCyl_zmin  =      123.600 = BackwardPIDRegion_zmin + 5*cm
< …
```
> refactor(pfRICH): reduce expansion volume by 5 cm

- templates/epic.xml.jinja2
This disables the `world_region` and `world_limitset` since they seem to be enabled in debug mode for some reason. Both limit sets were set to G4UserLimits defaults so they should not have had any effect anyway.
No.
No.
> fix: disable world_region and world_limitset

- .github/workflows/pr-backport.yml
This allows one to create labels with special name like `backport 23.07` that would automatically create a PR to duplicate change into a maintenance branch.
No.
No.
> ci: add GitHub action for PR backporting

- compact/ecal/barrel_sciglass.xml
This removes the hard-coded detector `id` for the EcalBarrelSciGlass and avoids potentially overlapping definitions.
No, unless you explicitly require system values of 4 in cellIDs.
No, unless you explicitly require system values of 4 in cellIDs.
> fix: use id="ECalBarrel_ID" in barrel_sciglass.xml

- .github/workflows/linux-eic-shell.yml
We create a list of detector configs in an early step and use it later on. This expands that functionality to create both a csv and json list. Both have now `epic_<configuration>` as format, consistent with other uses of `DETECTOR_CONFIG`.
This PR also avoids a large number of CI jobs on eicweb to trigger many geoviewers: each CI job was building the entire geometry again. We can avoid this, and just create the geoviewer artifacts in one go. We pass the csv list for that reason.
We also turn the matrix jobs for fast operations back into sequential jobs, avoiding the repeated overhead of starting a container environment.
TODO:
No.
No.
> ci: consolidate geoviewer job, include epic_ in detector_config json

- compact/definitions.xml
- compact/tracking/central_tracker_hybrid_v2.xml
- compact/tracking/definitions_craterlake.xml
- compact/tracking/mpgd_backward_endcap.xml
- compact/tracking/mpgd_forward_endcap.xml
- compact/tracking/silicon_disks.xml
- compact/tracking/support_service_assembly.xml
- compact/tracking/support_service_craterlake.xml
- compact/tracking/tof_endcap.xml
- configurations/craterlake.yml
- configurations/craterlake_tracking_only.yml
Backport #479 to 23.07 by hand since tag was not applied.
> Backport #479 to 23.07

- compact/far_forward/magnets.xml
- compact/far_forward/offM_tracker.xml
- compact/far_forward/roman_pots_eRD24_design.xml
- compact/far_forward/vacuum.xml
- compact/fields/beamline_10x100.xml
- compact/fields/beamline_10x275.xml
- compact/fields/beamline_18x275.xml
- compact/fields/beamline_5x100.xml
- compact/fields/beamline_5x41.xml
- src/CylindricalDipoleMagnet_geo.cpp
- src/ForwardRomanPot_geo.cpp
- src/OffMomentumTracker_geo.cpp
- src/hadronDownstreamBeamPipe.cpp
- src/magnetVacuumFF.cpp
Adds vacuum volumes throughout the FF region, from the B0 all the way to B2PF. There are currently cutouts for the sections where the OMD and RP are sitting, since this would create an overlap.
No, it should improve simulation results.
Yes, FF particles should be traversing vacuum for the vast majority of the z = 40m FF area inside the beam pipe.
> Fix ff vacuum

- compact/definitions.xml
- compact/hcal/forward_insert.xml
- src/InsertCalorimeter_geo.cpp
This changes the material, z-positions, and thicknesses of the absorbers in the forward Hcal insert to match the specifications of the LFHCAL absorbers.
Other slice component thicknesses are adjusted to accommodate these changes.
None that I know of.
Adjusts default geometry of the forward Hcal insert.
> feat: Align Hcal insert's absorbers with LFHCAL's

- compact/fields/beamline_10x110_H2.xml
- compact/fields/beamline_18x110_Au.xml
- compact/fields/beamline_18x110_H2.xml
- compact/fields/beamline_18x110_He3.xml
- compact/fields/beamline_18x110_Pb.xml
- compact/fields/beamline_5x110_H2.xml
- compact/fields/beamline_5x41_H2.xml
- compact/fields/beamline_5x41_He3.xml
- compact/fields/beamline_5x41_He4.xml
Use consistent lumi-related variable name in magnetic fields
> 516 bugfix use consistent lumi variable name in fields

- compact/tracking/mpgd_backward_endcap.xml
- compact/tracking/mpgd_forward_endcap.xml
This fixes the layer_pattern that Acts uses to interpret the MPGD sensitive surfaces in craterlake.
No.
No.
> fix: use correct layer_pattern for MPGD endcap surfaces

- src/FileLoader.cpp
- src/FileLoaderHelper.h
Fixes some edge cases, improves usability.
FileLoader: improve usage
---
Remove line starting with "name:" to not suggest that it's a parseable parameter.
Print which entry was not recognized during parsing.
Use cerr.
FileLoaderHelper: fix for when cache is a relative path
---
Previously
mkdir ./cache/sub/dir -p
echo q > cache/sub/dir/33b980fae79f456c
geoPluginRun -compact $DETECTOR_PATH/$DETECTOR_CONFIG.xml -plugin epic_FileLoader file:bar/baz url:https://example.com/ cache:./cache
Would result in
FileLoader       INFO  checking ./cache/./cache/sub
FileLoader       INFO  checking ./cache/./cache/sub/dir
Now ./cache produces a symlink in bar:
33b980fae79f456c -> ../cache/sub/dir/33b980fae79f456c
but $PWD/cache produces a symlink
33b980fae79f456c -> /path/to/cache/sub/dir/33b980fae79f456c …
> FileLoader improvements

- compact/far_forward/vacuum.xml
- src/magnetVacuumFF.cpp
This PR updates the magnet FF vacuum to remove gaps and overlaps and properly use CutTubes to connect the inner pieces together. Additionally, it has been modified to take the magnet locations as its primary input, and calculate everything relative to that, which should make maintenance easier in the long-run.
It should be noted that this volume is ONLY for the region between the end of the central beam pipe and the end of the b1apf magnet. The region occupied by the RP and OMD is handled separately.
No, it should further improve basic functionality.
Yes, it make the vacuum volume in the FF region more-continuous.
> Update ff magnet vacuum

- .github/workflows/linux-eic-shell.yml
Should be unused, since we don't have reverse dependencies (like ip6 repo) on GitHub anymore.
> linux-eic-shell.yml: remove workflow_dispatch functionality

- compact/materials.xml
- compact/solenoid.xml
This PR updates the ePIC Solenoid (MARCO) to the material specifications provided by the design team located at:
https://wiki.bnl.gov/EPIC/index.php?title=Experimental_Solenoid
No breaking changes 
No, it just updates the material budget for the MARCO solenoid.
This PR is a response to a material map run for me by Nicholas Schmidt at ORNL - you can see below that the solenoid is almost an interaction length, when it should be closer to 0.5 interaction lengths according to the designers:
The new material map reduces the material budget for the solenoid to be a bit closer to what we would expect:
Fully updated based on the material map from Renuka and Valerio dated 17 Sept 2023. The endcaps got a bit thicker, but most of the barrel is essentially the same. I removed the He layers that were …
> Update solenoid material budget

- src/magnetVacuumFF.cpp
Fixes memory leak caused be erroneous missing "deletes" for vector of DetElement*. DetElement changed to actual object instead of pointer.
No - fixed a bug.
No, just fixes the bug. Geometry renders the way it should.
> changed vector causing mem leak to vector of DetElements, rather than pointers

- bin/g4MaterialScan_to_csv
Improve the performance of g4MaterialScan_to_csv. It now does the scans without reloading geometry. It also outputs both X0 and Lambda in a single scan
No
No
> Improve the performane for bin/g4MaterialScan_to_csv

- compact/definitions.xml
- compact/far_forward/ZDC_SiPMonTile.xml
- configurations/zdc_sipm_on_tile_only.yml
- src/ZeroDegreeCalorimeterSiPMonTile_geo.cpp
Adds an SiPM-on-tile implementation of the ZDC Hcal, using similar technology to the forward calorimeter insert.
No, it does not introduce breaking changes
No, it does not change default behavior
To test this geometry,
Follow instructions in README.md to install epic and run source install/setup.sh
Run ./run_sim_hepmc_zdc inside the attached test_suite.zip in order to run a quick simulation of events in the proposed detector.
[test_suite.zip](https://github.com/eic/epic/files/12708021/test_suite.zip)
> Zdc SiPM-on-tile

- compact/far_forward/ZDC_SiPMonTile.xml
Corrected which axis the ZDC_SiPMonTile is rotated about.  This axis was set to z accidentally, but this pull request changes this to the y axis.
Makes the rotation of the ZDC SiPM-on-tile be along the y axis, rather than the z axis
No breaking changes.  This will modify the output of any code that uses the output of ZDC SiPM-on-tile simulations
Since the proposed SiPM-on-tile ZDC is not yet a part of the default configuration, this will not change the default behavior
> ZDC_SiPMonTile.xml: name rotation angle after Y-axis, not Z

- compact/hcal/forward_insert.xml
There are currently 4 layers of W/Sc in the forward HCal insert to match the layering of the surrounding LFHCAL. The correct layer structure for the HCal insert should be 1 front layer of Steel/Sc, 10 layers of W/Sc, 54 layers of Steel/Sc, 1 back layer of steel.
None.
Only the changes to the HCal insert listed above.
> feat - Increase number of W/Sc layers in forward HCal insert from 4 to 10.

- compact/definitions.xml
And we start to address the mismatches in https://github.com/eic/epic/pull/553. This one should be mostly isolate from other parts.
No.
No.
> fix: BackwardServiceGap_length:=124cm, HcalEndcapN_length:=45cm

- compact/definitions.xml
And we start to address the mismatches in https://github.com/eic/epic/pull/553. This one should be fairly harmless.
No.
No.
> fix: EcalEndcapN_zmin:=175cm

- bin/compare_detector_parameter_table
- templates/DetectorParameterTable.csv.jinja2
It adds a tool to compare two detector parameter tables
No
No
> Add a script to compare detector parameter tables

- bin/make_detector_parameter_table
- templates/DetectorParameterTable.csv.jinja2
Update the template for generating a detector parameter table from simulation constants.
The new template will be created based on the latest detector parameter table. (https://eic.jlab.org/Geometry/Detector/local/D/DetectorParameterTable-20230927.csv)
It only focuses on the comparable columns, so some columns such as "comments" will be dropped.
This PR partially resolves #552 
No
No
> Update the template for detector parameter table

- compact/definitions.xml
- templates/DetectorParameterTable.csv.jinja2
This adds a number of EcalBarrel variables to the detector parameter table template.
No.
No.
> fix: add EcalBarrel vars to template; EcalBarrel_rmin:=81cm; EcalBarrel_thickness:=35cm

- bin/compare_detector_parameter_table
A new table with some typo fixes is at https://eic.jlab.org/Geometry/Detector/Detector-20231013155913.html, but without csv format.
Since we expect more of the fixes to come, adding a support for extracting html table would be easier to update the comparison reports.
Related to issue #567 
No
No
> Add html format support in Detector Parameter Comparison

- compact/definitions.xml
Update the parameter for the backward service gap length
https://eic.jlab.org/Geometry/Detector/Detector-20231020152234.html
Related issue/PR: #559 
No
No
> update the backward service gap length

- compact/tracking/mpgd_backward_endcap.xml
- compact/tracking/mpgd_forward_endcap.xml
Fixes a typo in the readout segmentation for the endcap MPGD disks. Prior to this fix MPGD endcaps only reconstructed hits on the outer radius. This also fixes warning related to MPGD endcap volumes:
`Warning: :CentralTrackerSourceLinker] [warning] Can't convert globalToLocal for hit: vol_id=79186 det_id=82 CellID=844433520145746 x=-1.0392305 y=-284.53473 z=1480.3262`
No breaking changes, but MPGD disks will now have reconstructed hits across entire volume:
You just get the full hits now.
> fixed mpgd endcap readout segmentation

- compact/tracking/definitions_craterlake.xml
- compact/tracking/mpgd_outerbarrel.xml
Updates the outer MPGD barrel layer (the one integrated with the DIRC) to match the detector parameter table
- [x ] Bug fix (issue #568 )
This will probably cause an overlap with the DIRC volume, since the updated DIRC volume is not accounted for in this branch. 
Will likely trigger overlap errors between the DIRC and MPGD layer
> Update Outer MPGD barrel to match detector parameter table

- compact/far_forward/ZDC.xml
- compact/far_forward/ZDC_1stSilicon.xml
- compact/far_forward/ZDC_Crystal.xml
- compact/far_forward/ZDC_PbScinti.xml
- compact/far_forward/ZDC_WSi.xml
ZDC position and setup are updated:
1. The front-surface center of PbWO4 is at 35.8m from IP
2. Crystal, W/Si, and Pb/Scint modules are modified. The Pb/Sci module has been removed. 
The Pb/Si module is removed and therefore the signals from it can not be read.
No.
> Update the ZDC position and configuration.

- compact/definitions.xml
- compact/hcal/backward.xml
Updated sizes with new values from 2023/09/27 parameter table
Need to verify if it doesn't overlap with any beampipes
> Update with new parameter table - to solve issue #573

- compact/definitions.xml
The latest table https://eic.jlab.org/Geometry/Detector/Detector-20231031150001.html has a shorter service gap. This should have a knock-on effect on all forward detectors that ultimately depend on `ForwardServiceGap_zmin`
No
Yes
> forward service gap length in compliance with latest parameter table

- compact/materials.xml
Corrects default vacuum value to 1e-9 mbar
No.
Yes, less secondaries should be produced for FF protons and neutrons in the beam pipe vacuum.
> Update vacuum default density to 1e-15 g/cms to reflect RHIC vacuum - currently set to 100k mbar worse vacuum

- compact/definitions.xml
- compact/pid/drich.xml
- src/DRICH_geo.cpp
The updated geometry table requires the vessel rmax2 to be at 180 cm, but the designed communicated by Marco Contalbrigo requires the sensor box extended up to 185 cm. Also it requires the dRICH vessel length to be 122 cm (currently not implemented) . 
Marco is in communication with Tanja et al. to make sure the parameters are fine and afterwards this draft PR will be changed to the final PR.  
- [X ] Changes have been communicated to collaborators
Marco Contalbrigo and @c-dilks are communicated 
It should not make any difference. But if the barrel calorimeters are pushed downwards the overlap tests may fail. 
It should not make any difference. But if the barrel calorimeters are pushed downwards the overlap tests may fail. Other than this the dRICH performance should not change.
> reduced vessel rmax2 to 180 cm

- compact/definitions.xml
- compact/ecal/barrel_interlayers.xml
This PR related to the issue https://github.com/eic/epic/issues/552, and implements small changes in the Barrel ECal geometry to make it more realistic. The following changes has been implemented:
- SciFi/Pb z_min and z_max (and accordingly the full length) has been implemented according to https://eic.jlab.org/Geometry/Detector/Detector-20231031150001.html. 
- The total depth (envelope) of the calorimeter has been increased to 38 cm (from fixed 35 cm). 38 cm envelope is the correct one and fits both the SciFi and the 3 cm back Al plate.
- ~~In every AstroPix stave a carbon fiber slice has been added to mimic a bit better the material of the staves~~
No
Calorimeter (SciFi/Pb matrix) length, offset, and z_min z_max are in agreement with the geometry database:
Output of `npdet_info dump …
> Adjust Barrel ECal geometry according to the geometry database

- compact/definitions.xml
- compact/pid/dirc.xml
This implements following parameters for DIRC.
- Inner radius of 75.5 cm and outer radius of 78.6 cm for the DIRC bar box. The center of bar is at the average of those two values (r = 77.05 cm).
- DIRC readout starts at z = -303 cm. 
- Bar box ends at z = 185 cm. DIRC bar ends at z = 183 cm.
> update parameters for DIRC 

- compact/tracking/definitions_craterlake.xml
- compact/tracking/mpgd_outerbarrel.xml
Small updates to detector dimensions. Moved ACTS material binning to outer surface.
- [x ] Other: Update dimentsions
- [x ] Tests for the changes have been added
No
No
> Outer mpgd barrel geoupdate

- compact/far_forward/ZDC_Crystal_LYSO.xml
Changed name of hits to EcalFarForwardZDCHits, as requested by @veprbl when reviewing pull request 1221 in EICrecon.
Changes the name of the output bank for the LYSO section of the ZDC in order to match the convention used for the SiPM-on-tile section
Change of the name of the readout output of the ZDC LYSO
Users will need to change their code to use the new name of the ZDC Crystal LYSO detector, which is EcalFarForwardZDCHits
yes
> Update ZDC_Crystal_LYSO.xml:  Use readout name EcalFarForwardZDCHits

- .github/workflows/linux-eic-shell.yml
[Should benefit us since we have 4 cores available](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)
> linux-eic-shell.yml: use all available cores for cmake build

- compact/tracking/mpgd_outerbarrel.xml
Adjusts the active to dead area of the outer barrel MPGD and modifies the material budget.
- [x ] Other: Geometry/material update
- 
- [ x] Changes have been communicated to collaborators
None
No
> Outer mpgd barrel update

- compact/definitions.xml
- compact/ecal/barrel_interlayers.xml
- src/BarrelCalorimeterImaging_geo.cpp
Adds the 0.5 cm aluminum front support 
No.
No.
> feat: add front support to BarrelImaging Calorimeter

- configurations/full.yml
Fixes the default to use craterlake configuration.
The current full.xml based on arches.xml serves no practical purpose in ePIC.
Yes.
> configurations/full.yml: switch to craterlake.xml

- compact/pid/dirc.xml
- src/DIRC_geo.cpp
This adds the inter-MPGD/DIRC aluminum support rails. These are solid aluminum (for now), and somewhat arbitrarily placed due to lack of info on their position relative to the DIRC or MPGD. They are somewhat arbitrarily added to the DIRC as opposed to the MPGD, but I assume ultimately both will need to be connected with another bracket (of minimal X0).
The aluminum rails are approximated as a trapezoid that ignores the top 360/48 angle, and that extends to the bottom of the round rail (which isn't implemented here).
TODO:
No.
No.
> feat: add the inter-MPGD/DIRC aluminum support rails

- compact/fields/beamline_10x100.xml
- compact/fields/beamline_5x100.xml
Fixes the sign on a FF dipole which was incorrectly set.
- [ x] Bug fix (issue #__)
No, it corrects the transport for 100 GeV FF protons.
Yes.
> one of the FF dipoles had the wrong sign defined - fixed

- compact/ecal/barrel_interlayers.xml
Updated dimensions of the Barrel ECal:
Length w/o EoSB (end of sector box): 436.5 cm
Total length w/ EoSB: 466.5 cm
Length in h-going direction: 215 cm (Sector) + 15 cm (EoSB)
Length in e-going direction: 221.5 cm + 15 cm (EoSB)
Center offset: -38.75 cm
h-going: +176.25 cm
h-going + box: +191.25 cm
e-going: -260.25 cm
e-going + box: -275.25 cm
no
yes
> Adjust the length of BIC according to the newest baseline

- compact/definitions.xml
I believe, the #588 breaks the CalorimeterTrackProjections by removing `HcalBarrel_rmin` which is referenced in
https://github.com/eic/EICrecon/blob/fcd8c84b14a9f0e5e486329bd9d7b42938ea4f46/src/global/tracking/tracking.cc#L164
I think, the `rmin1`/`rmin2` naming is a bit confusing, would be nice to know what the `10.4*cm` offset stands for, and get some better names.
> HOTFIX: add back HcalBarrel_rmin

- compact/definitions.xml
> [Backport 24.03] HOTFIX: add back HcalBarrel_rmin

- compact/pid/dirc.xml
This PR re-enable optical materials in hpDIRC in anticipation of better control over optical photon propagation in the hpDIRC in npsim itself.
No.
Yes, optical photons enabled by default (but disabled by default in ddsim, and will in npsim).
> fix: re-enable optical materials in hpDIRC

- compact/tracking/mpgd_outerbarrel.xml
- compact/tracking/support_service_craterlake.xml
This PR adds the outer MPGD barrel support cylinder, which is 1 cm thick carbon fiber. Absent better info, it is defined here as sitting just inside the MPGD rmin, for the full length and offset of the outer MPGD barrel.
TODO:
No.
Yes, more material in front of outer MPGD barrel and barrel imaging calorimeter.
> feat: define and add inner detector barrel support cylinder (1 cm CF)

- compact/far_forward/ZDC_SiPMonTile.xml
This PR renames the HcalFarForwardZDC_SiPMonTile detector from a previous name with spaces and dashes.
No.
No. This name is not used for output collection names etc.
> fix: rename detector to HcalFarForwardZDC_SiPMonTile

- CMakeLists.txt
This PR prevents [dd4hep_configure_output](https://github.com/AIDASoft/DD4hep/blob/e52af7f770ec3e51460d832428f2cca214678e2a/cmake/DD4hepBuild.cmake#L328-L331) from overriding the `CMAKE_INSTALL_PREFIX` that we just set in case the user doesn't define it.
No.
Yes. The default install prefix (if not specified) will change from `${CMAKE_SOURCE_DIR}` to `${CMAKE_SOURCE_DIR}/prefix`.
> fix: tell dd4hep_configure_output which install prefix to use

- src/FieldMapB.cpp
This PR removes the forward/backward compatibliity that we introduced for the transition from DD4hep 1.25 to 1.26. Since we now require DD4hep 1.27 for other reasons (HexGrid segmentation), we don't have any backward compatibility anymore.
No.
No.
> fix: remove fieldmap type backward compatibility < dd4hep 1.26

- CMakeLists.txt
The build system writes the evaluated jinja templates (entrypoint xml files) into the source directory instead of a build directory. This PR moves these temporary build artifacts into the build directory instead.
TODO:
No.
Yes, no more xml files will be written to the source directory; `make install` or bust.
> fix: mv evaluated templates during build into CMAKE_CURRENT_BINARY_DIR

- compact/far_forward/B0_ECal.xml
Following the discussion at the Far-Fowrard working group meeting, the B0 Crystal length is now set to 20cm instead of 10cm. The Crystal material was changed from PbOW4 to LYSO.
More information is available here: https://indico.bnl.gov/event/21778/#20-updated-studies-on-b0-emcal
For now, the default choice is LYSO, while the final choice will be made in spring 2024 ([TIC meeting 3 Apr](https://indico.bnl.gov/event/22321/#11-planning-for-tdr-effort-ff))
The energy containment of the B0 Crystal detector will be improved from 60% -> 90%
no
The overlap of the crystals with the magnet bore were checked.
> Update B0 ECAL geometry

- compact/far_forward/B0_tracker.xml
- compact/tracking/mpgd_barrel.xml
- compact/tracking/mpgd_innerbarrel.xml
- compact/tracking/mpgd_outerbarrel.xml
- compact/tracking/silicon_barrel.xml
- compact/tracking/silicon_disks.xml
- compact/tracking/tof_barrel.xml
- compact/tracking/tof_endcap.xml
- compact/tracking/vertex_barrel.xml
add default material map binning for approach 2 in tracking detectors
- [ x] New feature (issue #__)
- [x ] Tests for the changes have been added
N/A
N/A
> add default material map binning for approach 2 

- .gitignore
Now that we have caused (#669) the default install directory to be `prefix/`, we should add it to the `.gitignore` so no one accidentally adds it to the repo. This PR adds `prefix/` to the project-wide `.gitignore` listing.
No.
No.
> fix: add `prefix/` to `.gitignore`

- src/DRICH_geo.cpp
This PR rotates the DRICH by 30 degrees. Per Marco's slides at https://indico.bnl.gov/event/22417/, e.g. slides 9 and 10, the DRICH has a readout box at the top, bottom, and at 2 and 4 o'clock, and 8 and 10 o'clock. That's different from where we had it before which was 0 degrees in phi, i.e. X axis, which is 9 o'clock. For an interaction region with a crossing angle, this matters, of course.
No.
Yes, it rotates the DRICH by 30 degrees.
> fix: rotate DRICH by 30 degrees

- compact/pid/drich.xml
- src/DRICH_geo.cpp
Until now the dRICH sensor boxes were a 5cm larger outer radius cylinder sticking out of the gas volume. This did not leave room for service routing between the sectors of the dRICH.
This PR modifies the sensor boxes (and envelope volume) to be a cylinder segment of configurable delta phi (set to 48 degrees to fit the sensors). The sections between the segments are conical (polycone), as per both services routing cad and recent TIC presentation.
TODO:
No.
Yes, adds azimuthally smaller sensor boxes, with side walls that have locally higher X0 expected
> feat: dRICH sensor boxes in more realistic sector segments

- compact/definitions.xml
Change the outer radius to 65 cm as communicated by Alex Enslinger. Hold merge until geometry table is updated (and documented in the commit. message)
No, it fixes problems with the latest (proposed) pfRICH implementation
Shouldn't.
> Change pfRICH outer radius

- configurations/craterlake_no_bhcal.yml
This PR fixes the [broken main CI pipelines](https://github.com/eic/epic/actions/runs/8462972314/job/23185174937#step:5:304) by ensuring that also epic_craterlake_no_bhcal conforms to the `far_forward:default:` syntax introduced in #679.
No.
No.
> hotfix: fix attempt to load non-existent far_forward/far_forward.xml

- CMakeLists.txt
This PR configures the epic build to use RPATH in the produced library libepic.so.
No.
No.
> fix: use DD4hep RPATH configuration for libepic.so

- scripts/view12/generate_eps
- scripts/view14/generate_eps
- scripts/view15/generate_eps
The current code depends on `-$zpos` to expand to a negated value of $zpos, which doesn't work for negative values.
> Use expr(1) for dawn views 12,14,15 to enable negative zpos

- configurations/ip6.yml
- configurations/ip6_extended.yml
The ip6 configurations were unable to be used to reconstruct tracks from the B0 surfaces without the DD4hep_SubdetectorAssembly which wraps around it which is defined in definitions_craterlake.
No
No
> Added definitions_craterlake to ip6 configurations

- .github/workflows/linux-eic-shell.yml
- scripts/material_map/.gitignore
- scripts/material_map/epic.py
- scripts/material_map/geometry_epic.py
- scripts/material_map/material_mapping_epic.py
- scripts/material_map/material_recording_epic.py
- scripts/material_map/material_validation_epic.py
- scripts/material_map/materialmap_config.py
- scripts/material_map/run_material_map_validation.sh
This PR adds automatic material map generation and validation (including comparison with what happens if we reuse the previous field map). It runs this in a pipeline job.
All this is based on @ShujieL's scripts in https://github.com/eic/snippets/tree/main/Tracking/material_map. It adds:
- automatic download of Acts source files,
- less copied code, more calling of Acts source,
- (therefore) less flexibility in file names.
No.
No.
> feat: material map generation and validation scripts and pipeline job

- CMakeLists.txt
Installing `setup.sh` in the prefix is not consistent with the linux filesystem hierarchy standard and leads to `/usr/local/setup.sh`. This PR installs `setup.sh` into e.g. `/usr/local/bin/thisepic.sh`, which is FHS compliant.
Next steps:
- Transition to using FHS location
- Add deprecation warning to old version (v24.MM++)
- Remove old version (v24.MM++)
No.
Not yet, but recommended default changes.
> feat: install setup.sh as FHS compliant bin/thisepic.sh

- compact/definitions.xml
- compact/display.xml
- compact/hcal/backward_endcap_flux.xml
- compact/hcal/barrel_flux_return.xml
- compact/hcal/forward_endcap_flux.xml
- compact/hcal/lfhcal.xml
- compact/materials.xml
- configurations/craterlake.yml
- configurations/craterlake_10x100.yml
- configurations/craterlake_10x275.yml
- configurations/craterlake_18x110_Au.yml
- configurations/craterlake_18x275.yml
- configurations/craterlake_no_bhcal.yml
- src/BarrelFluxReturn_geo.cpp
- src/EndcapFluxReturn_geo.cpp
- src/LFHCAL_geo.cpp
This PR adds the barrel flux return backlegs and spacers per the info in #693. Needed for hall background radiation studies. Also adds forward endcap flux return.
No.
Not really for any detector behavior.
> feat: add barrel flux return

- .github/workflows/linux-eic-shell.yml
Due to limitations in npdet_to_step, we disabled the HcalBarrel when exporting to STEP. With npsim 1.4.0, the issue with the HcalBarrel was [resolved](https://github.com/eic/npsim/pull/23).
This PR re-enables the HcalBarrel in npdet_to_step conversion, and it simplifies the logic to export all detector configs (for consistency and predictability).
TODO:
No.
No.
> fix: export all configs to STEP, use `part --level 1 HcalBarrel`

- compact/pid/drich.xml
The PR changes the azimuthal span of the extrusion box for the dRICH sensor from 48 degrees to 42 degrees. This will allow to have 18 degrees allowance for the services.
- [X ] Changes have been communicated to collaborators
Marco Contalbrig has been updated about the changes.
> dRICH Extrusion Box azimuthal span 42 degrees

- compact/calibrations.xml
Adds hpDIRC LUT to support https://github.com/eic/EICrecon/pull/1365
I pick @nathanwbrei 's fork over https://github.com/rdom/fastpid since the file got a minor update
```diff
diff --git a/hpdirc_positive.lut b/hpdirc_positive.lut
index a0c5841..ac5b96d 100644
--- a/hpdirc_positive.lut
+++ b/hpdirc_positive.lut
@@ -1,3 +1,21 @@
+# PDG code of the particle (e 11, pi 211, K 321, p 2212)
+11 211 321 2212
+
+# Charge (-1,1)
+1
+
+# Momentum [GeV/c]
+0.20 10.2 0.2
+
+# Polar angle [deg]
+25.0 161.0 1.0
+
+# Azimuthal angle [deg]
+0.0 30.5 0.5
+
+# Outputs columns are P[e], P[pi], P[K], P[p]
+# We ignore muons for now
+
11 1 0.20 25.00 0.00 0.0000 0.0000 0.0000 0.0000
11 1 0.20 25.00 0.50 0.0000 0.0000 0.0000 0.0000
11 1 0.20 25.00 1.00 0.0000 0.0000 0.0000 0.0000
```
> calibrations.xml: add hpdirc_positive.lut

- scripts/view1/generate_eps
- scripts/view11/generate_eps
- scripts/view12/generate_eps
- scripts/view13/generate_eps
- scripts/view14/generate_eps
- scripts/view15/generate_eps
- scripts/view2/generate_eps
- scripts/view20/generate_eps
- scripts/view3/generate_eps
- scripts/view4/generate_eps
- scripts/view5/generate_eps
- scripts/view50/generate_eps
- scripts/view6/generate_eps
- scripts/view7/generate_eps
- src/BarrelCalorimeterScFi_geo.cpp
Existence of /bin/bash is not guaranteed.
> scripts/view*: use bash from $PATH

- bin/generate_prim_file
- src/BarrelCalorimeterScFi_geo.cpp
psutil is an external package. I'd rather not have to worry about providing it.
> bin/generate_prim_file: use POSIX process groups instead of psutil

- compact/calibrations.xml
This updates to use the latest LUT from https://github.com/eic/epic-data/pull/12
No binning change, so we don't need any file renames.
> calibrations.xml: update to use latest tof.lut and pfrich.lut

- .github/workflows/linux-eic-shell.yml
This takes advantage of https://github.com/eic/detector_benchmarks/pull/20
> linux-eic-shell.yml: provide PIPELINE_NAME to detector_benchmarks

- compact/definitions.xml
- compact/ecal/barrel_interlayers.xml
Changes the size of Barrel ECal to the current envelope r=82 cm, length in z = 435 cm (active SciFi/Pb matrix).
Removes the Aluminum support planes of SciFi/Pb, and replaces them with thicker Carbon Fiber planes according to the newest geometry. 
no
yes
> Bic geo adjustment

- templates/thisepic.sh.in
This PR fixes the warning which said:
```
Warning: This script will cease to exist at '/opt/detector/epic-main/setup.sh'.
Please use the version at '/opt/detector/epic-main/thisepic.sh'.
```
to say the following instead:
```
Warning: This script will cease to exist at '/opt/detector/epic-main/setup.sh'.
Please use the version at '/opt/detector/epic-main/bin/thisepic.sh'.
```
No.
No.
> fix: correct warning message when using setup.sh

- templates/thisepic.sh.in
> [Backport 24.05] fix: correct warning message when using setup.sh

- .github/workflows/linux-eic-shell.yml
Trigger physics benchmarks directly. After https://github.com/eic/detector_benchmarks/pull/23, the downstream pipelines are not triggered, so we need to trigger them ourselves. This is a good opportunity start to triggering them earlier.
No
No
> linux-eic-shell.yml: trigger {physics,reconstruction}_benchmarks directly

- compact/far_forward/vacuum.xml
- src/magnetVacuumFF.cpp
This RP will fill the hadron line downstream with a vacuum to allow faster simulation of ion fragments.
Besides the execution time, this PR should keep the results unchanged. 
no
> Add more vacuum at z>40m

- compact/hcal/forward_insert.xml
Use only steel absorbers (replace tungsten layers with steel)
Changes the materials used in the calorimeter insert to use only steel layers for the aborbers, rather than using tungsten.
This could cause issues with EICrecon, since the sampling fraction will need to be changed in the code.  
Yes.
> HcalEndcapPInsert: Replace Tungsten layers with Steel layers

- src/FileLoaderHelper.h
This avoids triggering an exception every time path is updated:
```
cppyy.gbl.std.runtime_error: void dd4hep::sim::Geant4Kernel::loadGeometry(const string& compact_file) =>
runtime_error: filesystem error: in equivalent: Operation not supported ["calibrations/pfrich.lut"] ["calibrations/17a7536e11d8bc3f"]
```
No
No
> FileLoaderHelper: avoid supplying non-existent paths for fs::equivalent

- src/FileLoaderHelper.h
Removes lengthy output like
```
FileLoader       INFO  checking /opt/detector/epic-24.04.0/.spack/epic/repos/eic/packages/root
FileLoader       INFO  checking /opt/detector/epic-24.04.0/.spack/epic/repos/eic/packages/geant4
FileLoader       INFO  checking /opt/detector/epic-24.04.0/.spack/epic/repos/eic/packages/podio
FileLoader       INFO  checking /opt/detector/epic-24.04.0/.spack/epic/repos/eic/packages/dd4hep
FileLoader       INFO  checking /opt/detector/epic-24.04.0/.spack/epic/repos/eic/packages/epic
FileLoader       INFO  checking /opt/detector/epic-24.04.0/.spack/epic/repos/eic/packages/hepmc3
FileLoader       INFO  checking /opt/detector/epic-24.04.0/.spack/epic/archived-files
FileLoader       INFO  checking /opt/detector/epic-24.04.0/.spack/epic/archived-files/spack-build-xozo5y2 …
```
> FileLoaderHelper: reduce printout verbosity

- src/FileLoaderHelper.h
This PR modifies the FileLoader to remove the hash symlink unconditionally, whether broken or not. This should fix an issue where the symlink exists, points to another symlink, and that is a dead link.
No.
No.
> fix: remove FileLoader symlink unconditionally

- compact/display.xml
- compact/pid/pfrich.xml
- src/PFRICH_geo.cpp
- [x ] New feature (issue #__)
- [ x] Changes have been communicated to collaborators
No
No
> Initial commit on material

- bin/g4MaterialScan_raw_plot
- bin/g4MaterialScan_to_csv
Add a script to plot the scan results from "bin/g4MaterialScan_to_csv"
No, it's a tool
No
> Add a script to generate material scan plots

- configurations/backward_hcal_only.yml
- configurations/bhcal.yml
- configurations/craterlake_tracking_only.yml
- configurations/eeemcal_only.yml
- configurations/forward_detectors.yml
- configurations/forward_detectors_with_inserts.yml
- configurations/inner_detector.yml
- configurations/lfhcal_only.yml
- configurations/lfhcal_with_insert.yml
Simulating without field is not very useful. Most of the configurations are already doing this, we'd like to make things more consistent.
> configurations/: enable MARCO field for central single-detector configurations

- bin/g4MaterialScan_raw_plot
- bin/g4MaterialScan_raw_plot_2d
- bin/g4MaterialScan_to_csv
A script to generate 2D plots
No
No
> Add a 2D plot script for raw material scan

- .github/workflows/linux-eic-shell.yml
This PR causes changes in this repository to trigger a container rebuild on eicweb to catch errors like https://eicweb.phy.anl.gov/containers/eic_container/-/jobs/2955907 during container build which don't happen during detector benchmark custom build. Ultimately this should make the detector benchmark trigger unnecessary and simplify the workflows with which our benchmark pipelines are activated.
No.
No.
> feat: trigger eic_container build to catch build errors

- compact/pid/pfrich.xml
- src/PFRICH_geo.cpp
Move sensor material parameters to XML file
> Move sensor material parameters to XML file

- compact/display.xml
- compact/far_forward/roman_pots_eRD24_design.xml
- compact/fields/beamline_10x100.xml
- compact/fields/beamline_10x110_H2.xml
- compact/fields/beamline_10x275.xml
- compact/fields/beamline_18x110_Au.xml
- compact/fields/beamline_18x110_H2.xml
- compact/fields/beamline_18x110_He3.xml
- compact/fields/beamline_18x110_Pb.xml
- compact/fields/beamline_18x275.xml
- compact/fields/beamline_5x100.xml
- compact/fields/beamline_5x110_H2.xml
- compact/fields/beamline_5x41.xml
- compact/fields/beamline_5x41_H2.xml
- compact/fields/beamline_5x41_He3.xml
- compact/fields/beamline_5x41_He4.xml
- src/ForwardRomanPot_geo.cpp
This PR introduces changing RP geometry for the various beam energies, and updates the sensor size for the AC-LGADs to what we are planning to build.
- [ x] New feature (issue #__)
- [ x] Tests for the changes have been added (see PDF)
- [ x] Documentation has been added / updated
Changes will be presented at meetings on Monday and Tuesday (Oct 14th and 15th)
See slides here: https://www.dropbox.com/scl/fi/43mhwxeyvluku0w1ojqfr/new_roman_pots_geometry_10_9_2024.pdf?rlkey=w0wc0gzrk4d03e8uh9w8s0tq5&dl=0
No changes to user code needed, but users need to be careful to select the correct geometry when running dd4hep AND EICrecon. (https://chat.epic-eic.org/main/pl/rptqecge1jyctkkwa1454zy1mw)
I will hopefully address this issue in a PR …
> Update sensor geometry for rp

- configurations/inner_detector.yml
Would be nice to have that available for faster benchmarks.
> Add fEMCal to the inner_detector config

- compact/display.xml
- compact/far_backward/definitions.xml
- compact/far_backward/lumi/spec_ScFi_cal.xml
- src/EcalLumiSpecWScFi_geo.cpp
Updated the fiber holder material (brass -> steel) and dimensions (0.6mm thick -> 0.4mm thick) to reflect latest physical versions.
Updated the box material (aluminium - > plastic) and dimensions (y thickness 0.5cm -> 0.25cm).
-
> LumiCal Material/Dim updates.

- .github/workflows/linux-eic-shell.yml
Now that we trigger the geoviewer from the container job, along with other benchmarks, we don't need to trigger it directly (and it doesn't work to trigger it directly). E.g. https://eicweb.phy.anl.gov/EIC/benchmarks/geoviewer/-/jobs/3948345 triggered by https://github.com/eic/epic/actions/runs/11263980547/job/31323141281 just uses epic-main in the container, not the update-sensor-geometry-for-RP it should be using.
This PR removes the direct trigger of the geoviewer.
No.
No.
> fix(ci): don't trigger geoviewer directly

- compact/tracking/mpgd_outerbarrel.xml
Fixes the [issue #1659 in EICrecon](https://github.com/eic/EICrecon/issues/1659) where the last tracker hit was not being used in CKF.
[2024_11_06.pdf](https://github.com/user-attachments/files/17661610/2024_11_06.pdf)
- [ x] Bug fix: [EICrecon issue#1659](https://github.com/eic/EICrecon/issues/1659)
No breaking changes. Analyzers will now see all outer barrel MPGD hits included in the CKF.
No
> modify MPGD BOT ACTS tolerance

- .github/workflows/linux-eic-shell.yml
This PR runs the `npsim-dis` job inside gprofng, and uploads the call tree as an artifact.
No.
Yes, wraps npsim, may run slower.
> feat(ci): run npsim in gprofng, upload calltree

- .github/workflows/convert-to-step.yml
Reverts eic/epic#820
The zero surface message was a bug in root https://github.com/eic/eic-spack/pull/696. That means that the #820 was a hack, let's clean it up.
> Revert "convert-to-step.yml: fix for the new container"

- compact/tracking/mpgd_barrel.xml
- compact/tracking/mpgd_outerbarrel.xml
- src/MPGDCylinderBarrelTracker_geo.cpp
- Provision for 2D-strip readout for CyMBaL and Outer Barrel MPGDs.
- UV, as opposed to XY, readout for Outer Barrel MPGD.
- 2D-strip is not activated with current digitization factory => No change whatsoever.
- UV: Hit spatial distributions change slightly.
No statistically significant change.
> Barrel MPGDs: 2D-strip segmentation. Outer Barrel MPGD: UV segmentation.

- compact/ecal/backward_PbWO4.xml
- src/HomogeneousCalorimeter_geo.cpp
This updates tower geometry to match the latest CAD design.
No
Yes
> backward_PbWO4: adjust geometry to match latest CAD design

- compact/pid/dirc.xml
- src/DIRC_geo.cpp
This should not change the baseline geometry, but this allows to play with alternative values of the `DIRCBar_count_z` constant, which is set to 4 by default.
No
No
> DIRC: avoid hardcoding number of glued bars

- compact/tracking/definitions_craterlake.xml
update the link to new material map created by @bschmookler which addresses the artificial inconsistency introduced in 24.10 due to geometry change. See performance study at https://indico.bnl.gov/event/26553/
New map stored at https://eicweb.phy.anl.gov/EIC/detectors/athena/-/issues/153 as usual.
- [ x] Bug fix (issue #__)
- [ x] Tests for the changes have been added
N/A
It will bring the tracking performance back to normal for any simulation with ePIC 24.10 or newer.
> Update material map

- .github/workflows/convert-to-step.yml
This PR adds the AstroPix chips as lowest level detail in the EcalBarrelImaging STEP files.
Increases file size of epic_imaging_only.stp from 440 kB to 650 kB. But now includes the AstroPix instead of solid trays.
No.
No.
> feat: export down to AstroPix chips in EcalBarrelImaging STEP

- src/PFRICH_geo.cpp
This PR fixes a likely typo in the PFRICH geometry plugin. It is likely that the line `pdboxDE.setPlacement(pdboxPV)` was copied and only the argument changed, but not the object itself.
Previously:
```cpp
DetElement pdboxDE(sdet, "pdbox_de", 0);
pdboxDE.setPlacement(pdboxPV);
// ...
DetElement qdboxDE(sdet, "qdbox_de", 0);
pdboxDE.setPlacement(qdboxPV);
```
New:
```cpp
DetElement pdboxDE(sdet, "pdbox_de", 0);
pdboxDE.setPlacement(pdboxPV);
// ...
DetElement qdboxDE(sdet, "qdbox_de", 0);
qdboxDE.setPlacement(qdboxPV);
```
No.
No.
> fix: likely typo in PFRICH_geo.cpp

- src/FileLoaderHelper.h
This PR fixes an infrequent recurring issue in the handling of calibrations and fieldmaps. It occurs when a file handle symlink is pointing to a hash symlink that is itself pointing to a non-existent location (the following is the situation after the error occurs):
```
jug_dev> wdconinc@menelaos:~/git/epic$ ls -al calibrations/
total 152616
drwxr-xr-x  6 wdconinc wdconinc     4096 May 12 13:16 .
drwxrwxr-x 32 wdconinc wdconinc     4096 May 12 13:16 ..
lrwxrwxrwx  1 wdconinc wdconinc      109 May 12 13:16 0820c1b054653fef -> /opt/detector/epic-git.63e5b941500f64c35449c29850b0bd60717adb2c_main/share/epic/calibrations/0820c1b054653fef
-rwxrwxrwx  1 wdconinc wdconinc      178 Apr 27 11:14 5a54959cc63eeb5b -> /opt/software/linux-debian12-x86_64_v2/gcc-12.2.0/epic-git.4f29e576c85b7342bf0b3b3f032 …
```
> fix: handle dead symlinks in FileLoaderHelper

- compact/central_beampipe.xml
- src/EndcapFluxReturn_geo.cpp
- src/ForwardRomanPot_geo.cpp
- src/IP6BeamPipe.cpp
This PR fixes the recently introduced memory leak. VisAttributes are owned by the xml description. It also fixes a few other memory leaks, in particular due to interrupted DetElement trees, and forgotten `add` after `clone`.
No.
No.
> fix: avoid memory leaks in various geometry plugins

- compact/central_beampipe.xml
- compact/definitions.xml
- compact/far_backward/beamline_extension_hadron.xml
- compact/far_backward/definitions.xml
- compact/far_forward/definitions.xml
- templates/epic.xml.jinja2
Fixes an airgap in the Far-Backward beamline by centralizing the definitions for the beampipe ends.
TaggerTrackerTracks have gone missing from the EICRecon output since the IP6 beampipe update. A visual inspection shows an air gap between the central beampipe and the current far-backward electron beamline (and an overlap with the incoming hadron extension). The air is _hopefully_ responsible for breaking the electron track reconstruction...
Centralizing the variables used to define the positions of the ends should fix this and stop something like this happening in the future. The small gap in the incoming hadron beamline is much less important.
A more detailed revision of the far-backward beamline is in progress but this is required sooner.
Hopefully recovers a full vacuum
> Centralize IP6 Beampipe constant definitions

- compact/definitions.xml
- compact/ecal/bic/bic.xml
- compact/ecal/bic/bic_layer1_only.xml
- configurations/craterlake_material_map.yml
- src/BarrelCalorimeterImaging_geo.cpp
This PR adds tracking support to the first AstroPix layer of the Barrel Imaging Calorimeter (well, technically all of the layers).
With this geometry, and with https://github.com/eic/epic/pull/710, we now see the hits from the first layer of the BIC be part of reconstructed tracks (BIC first layer is avg at 84 cm rmin + 0.5 cm inner support plate + 0.75 cm to middle of tray):
No.
No.
> feat: initial EcalBarrelImagingTracker support

- .github/workflows/linux-eic-shell.yml
There is no need to do this, every commit has to pass eicweb tests before merging anyway.
> linux-eic-shell.yml: avoid building container for main branch

- compact/far_backward/lumi/lumi_magnets.xml
- compact/fields/marco.xml
- src/FieldMapB.cpp
This PR makes the specification of rotation and translation for FieldMapB entities optional, and does not do any trivial rotation and translation when they are not set. VTune profiling indicated that there was a 1% speed-up opportunity in avoiding the ROOT::Math::XYZPoint transformations (as well as the delayed phi determination). It is a bit of a micro-optimization, though, but `fieldComponents` is still the highest nail that is entirely under our control in simulations (because poorly defined geometry doesn't show up that way...).
No.
No.
> feat: make FieldMapB rotation and translation optional

- compact/calibrations.xml
Adds a third neural network to the calibrations which behaves the same as the previous onnx implementation but internalizes the projection of the vector onto a plane (dimension reduction). This has been trained using the benchmark script but needs to be added before the benchmark workflow can be properly implemented as a chicken and egg situation.
The other two implementations will be removed once this becomes the primary method used in reconstructing the lowQ2 electrons for ReconstructedParticles.
No
Will download an additional file from epic-data when the geometry is loaded/
> Add another low-q2 reconstruction onnx to calibrations

- compact/calibrations.xml
The link to epic-data for the new low-q2 onnx file linked to the html site rather than the raw file
No
Downloads the raw onnx rather than html site...
> Fix new low q2 onnx blob to raw

- .github/workflows/check-tracking-geometry.yml
- compact/ecal/bic/bic.xml
- src/BarrelCalorimeterImaging_geo.cpp
This PR moves the BIC 1st layer into a separate layer for Acts conversion purposes. With this modification, `/usr/bin/time -v root -b -q "scripts/test_ACTS.cxx+(\"${DETECTOR_PATH}/epic_craterlake.xml\")"` has a max RSS of 2.3 GB (down from 2.75 GB).
No.
No.
> fix: put BIC 1st layer in separate envelope for Acts conversion

- compact/calibrations.xml
- src/FileLoaderHelper.h
Allows the `epic_FileLoader` plugin to load files from `xrootd` servers. Using `Low-Q2_Steering_Reconstruction.onnx` as an example.
No
Downloads Low-Q2_Steering_Reconstruction.onnx  from the jlab xrootd server rather than the epic-data github repository
> Load Low-Q2_Steering_Reconstruction.onnx from xrootd server

- .github/dependabot.yml
This PR adds @eic/epic-detector-geometry-review as reviewer to dependabot updates.
> ci: Add reviewers to GitHub Actions Dependabot config

- .github/workflows/linux-eic-shell.yml
- compact/tracking/silicon_disks.xml
- configurations/craterlake_material_map.yml
- scripts/material_map/epic.py
- scripts/material_map/geometry_epic.py
- scripts/material_map/material_mapping_epic.py
- scripts/material_map/material_recording_epic.py
- scripts/material_map/material_validation_epic.py
- scripts/material_map/run_material_map_validation.sh
This PR is a minimal set of changes to bring the validate-material-map workflow back from the dead. It disables BIC and B0 for now, but at least should get us back on the road.
No.
No.
> fix: resolve material map scripts for Acts 39 (v2)

- compact/tracking/definitions_craterlake.xml
Update the SVT NDisk4 position to -102cm to better match the latest detector envelope. See https://indico.bnl.gov/event/27186/
- [ x] New feature (issue #__)
> Update the SVT NDisk4 position to -102cm

- compact/tracking/tof_endcap.xml
- src/EndcapTOF_geo.cpp
There is currently nothing between the front and back layers of FTOF. However, dRICH group wants to study the effect of FTOF material and having the right material is important for their study. 
A uniform slab of carbon foam of width 1 cm is now sandwiched between the two layers. Details such as cooling tubes will be added later. The width of the support structure is given by slide 6 of https://indico.bnl.gov/event/24949/attachments/57520/98759/ePICTOF_WP2_FTOFLayout_09272024v2.pdf
The thickness of the module board and PCB are not final and will be changed in the future. 
No
No
> Add support materials to FTOF

- compact/tracking/definitions_craterlake.xml
- compact/tracking/mpgd_barrel.xml
- compact/tracking/mpgd_outerbarrel.xml
- src/BarrelPlanarMPGDTracker_geo.cpp
Check that MPGD simulation geometry matches CAD drawing ([CAD File](https://indico.bnl.gov/event/27186/contributions/104526/attachments/60501/104351/EPIC%20Active%20Area%20Envelope%20-%2003-20-2025.pdf))
Doesn't break anything, but geometry is changed and material map will need to be reproduced.
MPGD hit positions will be modified due to geometry changes
> MPGD Geo Validation

- .github/release.yml
Same as https://github.com/eic/EICrecon/blob/67a5b420519734a4fb128d9a8e2d7aa0a61fc6d4/.github/release.yml
> Add .github/release.yml
