- .github/workflows/linux-eic-shell.yml
This will allow dispatching this workflow from another repository.
> GitHub Actions: enable workflow dispatch

- templates/setup.sh.in
> setup.sh.in: add macOS support

- bin/generate_prim_file
- bin/make_dawn_views
- bin/make_detector_configuration
- bin/make_detector_parameter_table
- bin/make_images
> bin: use python3 in shebangs

- src/DRICH_geo.cpp
To be merged into #42, for @cpecar
If the sensor is resized, the segmentation must also be resized,
otherwise there will be too many pixels for the readout encoder.
> fix (dRICH): resolve readout buffer overflow for `DRICH_debug_optics==4`

- README.md
> README.md: suggest -DEPIC_ECCE_LEGACY_COMPAT=OFF

- .github/workflows/generate-weekly-meeting-slides.yml
> ci: add weekly meeting slide config

- CMakeLists.txt
Default should be `OFF`, not undefined
> fix: cmake option `IRT_AUXFILE`

- compact/tracker/mpgd_barrel.xml
updated resolutions in mpgd_barrel.xml from 50um to 150um
> updated resolutions in mpgd_barrel.xml from 50um to 150um

- compact/tracker.xml
- compact/tracker/mpgd_barrel.xml
Modified material in the inner and outer barrel layers, since exact material budget is not setup yet.
Overall material budget for inner MPGD barrel is now ~0.5% X0 and ~1% X0 for outer barrel layer.
> Modified material in mpgd_barrel.xml

- compact/tracker.xml
- compact/tracker/mpgd_barrel.xml
mposik1983 will be the point of contact for micro pattern gas detectors. This information has been added to mpgd_barrel.xml
> Added POC info to mpgd_barrel.xml

- compact/definitions.xml
- compact/tracker.xml
- compact/tracker/mpgd_barrel.xml
- compact/tracker/silicon_barrel.xml
- compact/tracker/silicon_disks.xml
modified a few tracker xml to update one disk radius and some layer_material binning for Acts material map.
> A few adjustments for material map

- compact/drich.xml
- src/DRICH_geo.cpp
Close #108 
- testing externally with https://github.com/eic/drich-dev/blob/geo-reader/src/draw_segmentation.cpp
- see #108 for notes and more details
No
No
> fix(dRICH): correct the sensor segmentation offset and grid size

- compact/tof_barrel.xml
- compact/tof_endcap.xml
TOF geometry updated (see issue #135) based on EIC Detector database tagged as 20220905113308.
Conflict with service cone to be resolved.
> TOF geometry update

- compact/definitions.xml
- compact/materials.xml
definition.xml and materials.xml are updated following the replacement of ZDC in eic/ip6.
(See pull request in eic/ip6 "replacement of the ZDC structure" https://github.com/eic/ip6/pull/26)
none
Will not work properly until the PR in eic/ip6 is merged.
> Modifications for ZDC replacement

- compact/definitions.xml
- compact/tracker.xml
- compact/tracker/mpgd_barrel.xml
Introduce new definitions and positions into the hpdirc branch.
No.
No.
> Updated DIRC and OuterMPGDBarrel definitions and positions

- .github/workflows/linux-eic-shell.yml
DD4hep has the checkGeometry tool which can be used to produce histograms of time per track spent per volume. This workflow produces these histograms and log output for both fast and full geometry.
No.
No.
> feat: run geometry checks

- compact/definitions.xml
- compact/tracker.xml
- compact/tracker/mpgd_barrel.xml
- compact/tracker/mpgd_dirc.xml
- src/MPGDDIRC_geo.cpp
Change outer MPGD layer to bar geometry and build using assembly.
Yes. Outer MPGD layer is not implemented into ACTS
Yes. Outer MPGD layer is not implemented into ACTS
> 76 outer mpgd layer geometry change 1

- .github/workflows/linux-eic-shell.yml
The views are currently locked as artifacts which cannot easily be looked at (requires download and unzip). This deploys the views to a web page.
No.
No.
> ci: deploy views to eic.github.io/epic/

- README.md
Now that we are publishing the artifacts to gh-pages, we should link the correct image into the README.md
No.
No.
> doc: use the correct (main) image in the README.md

- compact/drich.xml
For consistency with the menagerie.
No
No
> fix(dRICH): increase snout entrance radius from 95 -> 110 cm

- compact/tracker.xml
Update material map , see https://eicweb.phy.anl.gov/EIC/detectors/athena/-/issues/153#note_21089
> new material map 

- .github/workflows/linux-eic-shell.yml
We test the build only with gcc, but the container has clang installed as well. This builds the code with clang as well to catch some bugs, e.g. #209.
No.
No.
> feat(ci): also test build in clang

- .github/workflows/linux-eic-shell.yml
Building the geometry plugins is on the critical path. Faster jobs will result in faster pipeline completion. We have two CPUs on runners, so we should use them.
No.
No.
> ci: build faster with -j 2

- compact/definitions.xml
- compact/mrich.xml
- compact/tracker.xml
- compact/tracker/support_service_assembly.xml
Remove outer detail from forward tracker support, and make backward tracker support discontinuous
Also fixes some of the central detector volume allocations.
Closes #208
> Fix tracker support overlaps

- .github/workflows/linux-eic-shell.yml
This runs overlap checks on both sciglass and imaging geometry
No.
Yes, more tests, may take longer (due to queuing).
> ci: run overlap checks on both detector configs

- .github/workflows/linux-eic-shell.yml
In my attempt at speeding up the various merge pipelines, two consecutive merges introduced a logical conflict by defining conflicting workflow strategies, https://github.com/eic/epic/actions/runs/3294550229/workflow#L331. This fixes the conflict.
No.
No.
> hotfix: merge CI matrix strategy defs in same step

- templates/epic.xml.jinja2
Not sure how I failed at copy & paste in #251 ... this now adds the vertex barrel again as well.
Yes. `epic.xml` will again include vertex barrel.
Yes. `epic.xml` will again include vertex barrel.
> hotfix: re-add also vertex barrel

- src/EndcapTOF_geo.cpp
Remove single line of debugging output that was printed every time.
No.
No.
> fix: remove debugging output in EndcapTOF

- .github/labeler.yml
- .github/workflows/labeler.yml
Enables https://github.com/actions/labeler
No
No
> .github: add actions/labeler for automatic PR labeling

- .github/labeler.yml
> .github/labeler.yml: fix yaml syntax

- src/SciGlassCalorimeter_geo.cpp
The approach is to take an intersection after doing a transverse shift, not before.
No
No
> SciGlassCalorimeter: fix a small (1e-4) extrusion

- compact/solenoid.xml
This introduces the corrected field maps for 1.7 T, which have the correct units.
No.
Yes, simulations will run with corrected magnetic field map.
> feat: updated magnetic field map

- compact/solenoid.xml
> solenoid.xml: use magentic field versioned in eic/epic-data

- src/FileLoaderHelper.h
Files stored on GitHub and accessed with `raw` links require a redirect to be followed.
No.
Yes, re-enable magnetic field...
> fix: curl --location to follow github raw redirect

- compact/ecal/barrel_sciglass.xml
- src/BarrelCalorimeterSciGlass_geo.cpp
The sector-module-slice was temporarily introduced due to a failing benchmark.
Yes
Yes
> SciGlassCalorimeter: revert back to sector-row-tower readout

- compact/ecal/barrel_sciglass.xml
- src/BarrelCalorimeterSciGlass_geo.cpp
Introduces an option to specify the tower material.
No
No
> SciGlassCalorimeter: specify tower material in the compact file

- compact/fields/marco.xml
- compact/solenoid.xml
- configurations/dirc_only.yml
- configurations/drich_only.yml
- configurations/mrich_only.yml
- configurations/pfrich_only.yml
- configurations/pid_only.yml
- configurations/sciglass_only.yml
- configurations/tof_endcap_only.yml
- configurations/tof_only.yml
- configurations/tracking_only.yml
- configurations/vertex_only.yml
- templates/epic.xml.jinja2
Enables field for single-detector configurations
No
No
> Separate field from solenoid material geometry

- src/DRICH_geo.cpp
> dRICH: add airgap volume between aerogel in filter

- templates/DetectorParameterTable.csv.jinja2
Forgot to change `DRICH_Length` -> `DRICH_length` in the param table template
no
no
> fix: `DRICH_length` for `dump-parameters` CI job

- compact/tracking/definitions.xml
- compact/tracking/definitions_brycecanyon.xml
- compact/tracking/mpgd_dirc.xml
- configurations/18x275.yml
- configurations/arches.yml
- configurations/arches_no_barrel_hcal.yml
- configurations/brycecanyon.yml
- configurations/brycecanyon_no_barrel_hcal.yml
- configurations/central.yml
- configurations/full.yml
- configurations/hcal_gdml.yml
- configurations/imaging.yml
- configurations/inner_detector.yml
- configurations/tracking_only.yml
- src/MPGDDIRC_geo.cpp
- templates/epic.xml.jinja2
Integrates acts tracking for mpgd dirc
No
No
> Acts tracking for MPGD DIRC

- .github/workflows/linux-eic-shell.yml
Both of these jobs are very similar, so we merge them into a single matrix job (similar to what's already done in EICrecon CI).
No.
No.
> ci: merge build-gcc and build-clang jobs

- src/DRICH_geo.cpp
Minor bug fix, when using the dRICH in "optics debugging mode", a special mode to check the Cherenkov photon optics.
no
no
> fix(DRICH): undefined `PlacedVolume` usage when `DRICH_debug_optics==1`

- src/DRICH_geo.cpp
Remove dead code and make the mirror parameterization simpler. No changes to the parameters.
no
no
> cleanup: simplify dRICH mirror focusing

- src/BarrelHCalCalorimeter_geo.cpp
Looks like some parts may have been inherited from the BarrelCalorimeter geo.
No
No
> BarrelHCalCalorimeter: remove some redundant code

- compact/far_backward/lumi/directPC.xml
This fixes an issue that surfaced when using the xerces-c parser.
No.
No.
> hotfix: rm spaces in readout id

- compact/far_backward/lumi/spec_homo_cal.xml
Another one, of course... (Self-correlation in this code base is high). This is the only one left as far as I could find.
No.
No.
> hotfix: rm spaces in readout id (2)

- compact/hcal/lfhcal.xml
- src/LFHCAL_geo.cpp
This PR introduces the new updated geom with the main pieces for the LFHCal using the buried SiPM geometry.
> LFHCal updated geom

- compact/display.xml
- compact/tracking/tof_endcap.xml
- src/EndcapTOF_geo.cpp
This PR adds a fully rewritten detailed geometry for the forward TOF detector system. It has been checked for overlaps and functionality within ACTS.
> rewritten geometry for forward TOF with full ACTS functionality

- compact/tracking/tof_endcap.xml
- src/EndcapTOF_geo.cpp
Very minor changes to FTOF. Mainly change from Aluminum to Copper for readout material.
- [x ] Other: __
> minor material and visualization changes for FTOF

- .github/workflows/linux-eic-shell.yml
- README.md
- _config.yml
- _layouts/geoviewer.html
- reports/craterlake_views.md
This switches the README.md and CI pipelines from arches/brycecanyon to brycecanyon/craterlake.
No.
No.
> fix: shift to brycecanyon, craterlake

- compact/definitions.xml
- compact/display.xml
- compact/ecal/barrel_interlayers.xml
- compact/unused/ecal_barrel_hybrid.xml
- src/BarrelCalorimeterImaging_geo.cpp
- src/BarrelCalorimeterScFi_geo.cpp
Implements fan blades at 10 degrees, except for the innermost layer where they are still just flat on the inner surface of the Pb/ScFi.
No.
Yes. New imaging layers layout.
> feat: implement fan blade imaging calorimeter staves

- compact/display.xml
- compact/ecal/barrel_interlayers.xml
This should speed up dawn views to previous level of performance.
No.
No.
> fix: speed up EcalBarrel display and dawn views

- .github/workflows/pr-backport.yml
Can't use github user to submit PRs with Github Actions
Similar to https://github.com/eic/EICrecon/pull/954
> pr-backport.yml: add github token

- .github/workflows/linux-eic-shell.yml
Fixes more broken pipelines on eicweb... https://eicweb.phy.anl.gov/EIC/benchmarks/geoviewer/-/jobs/1999940
No.
No.
> fix(ci): pass DETECTOR to eicweb triggers

- .github/workflows/linux-eic-shell.yml
- README.md
Craterlake is now the official detector configuration for the project. There is no need to keep simulating brycecanyon for everything.
No.
No.
> feat: remove epic_brycecanyon as main configuration

- src/FieldMapBrBz.cpp
> FieldMapBrBz: fix axial rotation of the B field vector

- compact/definitions.xml
And we start to address the mismatches in #553. This one should actually be harmless.
No.
No.
> fix: ForwardServiceGap_thickness:=13.6cm

- .github/workflows/linux-eic-shell.yml
- README.md
Write a html version of the detector parameter table.
TODO:
No.
No.
> feat: write detector_parameter_table.html

- configurations/calorimeters.yml
- configurations/central.yml
- configurations/inner_detector.yml
- configurations/pid_only.yml
Some configurations are outdated, this PR updates them. Partially resolve #532 
No
No
> Update the configurations

- compact/tracking/mpgd_backward_endcap.xml
- compact/tracking/mpgd_forward_endcap.xml
- templates/DetectorParameterTable.csv.jinja2
Updates MPGD disks to match detector parameter table
- [] Documentation update
- [ x] Changes have been communicated to collaborators
There should be no breaking changes 
No
> Mpgd disks parameter table update

- src/hadronDownstreamBeamPipe.cpp
Beam pipe thickness was set too high at 1cm. 
- [x ] Bug fix (issue #__)
No.
Yes, more particles will make it to the ZDC unaffected.
> update FF beampipe thickness from 1cm to 2mm

- scripts/test_ACTS.cxx
Updates the test_ACTS.cxx script for the new Acts version interfaces. Loggers are now passed by reference, not as a log level.
No.
No.
> fix: update test_ACTS.cxx for new Acts interfaces

- compact/definitions.xml
Change the fECal outer radius to 195 cm according to the detector geometry Table.
No breaking changes. Users do not need to update their code.
No.
> Change fECal outer radius to 195 cm (Table value)

- compact/definitions.xml
- compact/pid/pfrich.xml
Adjust parameters to conform to https://eic.jlab.org/Geometry/Detector/Detector-20231031150001.html
The volume is shortened, the inner radius enlarged, so in general no problems expected. But it's also shifted by 1mm toward 0, so other systems need to respect the change in `CentralTrackingRegionN_zmax` to avoid overlap.
Yes
> Issue 570 pfrich dimensions

- configurations/inner_detector.yml
Update the configuration so it does not report false overlaps in #586
> Update configuration for inner detectors

- compact/far_forward.xml
Removed a commented line
Removes a commented line from this file (which was commented out in a recent push).  
- Removal of a commented line
- [N/A] Tests for the changes have been added
- [N/A] Documentation has been added / updated
no
no
> Removed a commented line in far_forward.xml

- .github/dependabot.yml
Enable dependabot for github-actions upgrades.
> feat: enable dependabot.yml

- .github/workflows/linux-eic-shell.yml
This updates all github actions which started to emit warnings recently due to being based on nodejs v16.
No.
No.
> fix(ci): update various github actions for nodejs v20

- .github/labeler.yml
> labeler.yml: fix config for v5

- scripts/test_ACTS.cxx
I am seeing weird behavior with a conversion that works, but then a visitSurfaces call that fails. We might as well test this in CI. This PR cleans up the test by removing unused code, and adds the new test.
No.
No.
> fix: cleanup test_ACTS and add visitSurfaces test

- compact/tracking/tof_endcap.xml
fix for tof endcap reso, as requested by the TOF group
> fixed tof endcap y-resolution to correct value

- configurations/craterlake_material_map.yml
This PR adds a configuration with all geometry that is to be included in the material map for Acts track reconstruction.
No.
No.
> feat: add craterlake_material_map.yml configuration

- .gitignore
This PR causes git to ignore the gdml/ and calibrations/ directories so they are not accidentally checked in.
No.
No.
> fix: ignore gdml/ and calibrations/

- README.md
This PR updates the front-page README.md with the tgeo and step file links, and places the image 'above the fold' with links by side. Some poor alignments, but didn't want to shrink the image even further.
No.
No.
> doc: update README.md with tgeo and step file links

- .github/workflows/linux-eic-shell.yml
- bin/acts_geo_check
Adds tests to check if more configurations are pass the check-tracking-geometry check.
Initially this is before the epic_ip6 has been updated so should fail the test but probably initially won't. This should be followed by a change to acts_geo_check to cover the case or a request to change the logger level of messages which should cause it to fail.
No
No
> Extended configs tested by check-tracking-geometry

- compact/calibrations.xml
- templates/epic.xml.jinja2
This PR adds a place to put calibrations artifacts in a place that allows them to be propagated to cached and other configurations. Yes, it's xml, not json, but at some point later we can switch that.
No.
No.
> feat: add calibrations.xml

- .git-blame-ignore-revs
This PR adds the clang-format commit to git blame ignore revs.
No.
No.
> feat: add clang-format to .git-blame-ignore-revs

- compact/calibrations.xml
This adds LUTs for use in EICrecon.
> calibrations.xml: add LUTs for drich, pfrich and tof

- src/BarrelCalorimeterScFi_geo.cpp
- src/PFRICH_geo.cpp
Fixes a minor regression from the latest geometry update in #664.
Fixes: #706
> PFRICH: restore sensititvity to hits

- compact/calibrations.xml
This updates calibration to the latest revision https://github.com/eic/epic-data/commit/f83bf74a79ba4cc71b459a65ba48d3a68deb0ae3
> calibrations.xml: update pfrich.lut again

- compact/calibrations.xml
This is a version with both charges, as found on dropbox.
> calibrations.xml: add hpdirc.lut.gz

- compact/calibrations.xml
Introduces the tmva low-q2 model file to the geometry calibrations so it gets downloaded when the geometry is loaded by eicrecon
No
No
> Added tmva model to file loader

- compact/fields/marco.xml
This updates the fieldmap to the May 2024 version at https://wiki.bnl.gov/EPIC/index.php?title=Experimental_Solenoid.
No.
Yes, updated fieldmap will be used.
> feat: update fieldmap to MARCO v.7.6.2.2.11

- compact/tracking/definitions_craterlake.xml
New material map for craterlake with updated service cones. See https://eicweb.phy.anl.gov/EIC/detectors/athena/-/issues/153#note_27320
Update material map for the new service cone
- [x ] New feature (issue #__)
- [x ] Tests for the changes have been added
N/A
it should improve the EICrecon/ACTS tracking performance.
> Update material map

- compact/calibrations.xml
This incorporates https://github.com/eic/epic-data/pull/21
No
No
> calibrations.xml: update pfRICH LUT

- compact/ecal/backward_PbWO4.xml
- src/HomogeneousCalorimeter_geo.cpp
Implements implicit suggestion from https://github.com/eic/epic/pull/704#discussion_r1625108217
> EEEMCal: reparametrize inner collar in terms of proton ring x offest

- CMakeLists.txt
- cmake/git_version.cmake
- templates/epic.xml.jinja2
- templates/thisepic.sh.in
- templates/version.xml.in
This uses same code as in EICrecon. This partially undoes of #733, geometry version is useful.
No
No
> cmake: set CMAKE_PROJECT_VERSION from git, add it back to thisepic.sh

- configurations/mrich_only.yml
> fix: rm mrich_only.yml

- compact/tracking/definitions_craterlake.xml
> [Backport 24.08] Update material map

- compact/tracking/mpgd_outerbarrel.xml
> [Backport 24.11] modify MPGD BOT ACTS tolerance

- compact/calibrations.xml
See https://github.com/eic/epic-data/pull/22
This is needed to enable https://github.com/eic/EICrecon/pull/1618
> calibrations.xml: add calibrations/onnx/EcalEndcapN_pi_rejection.onnx

- .github/workflows/convert-to-step.yml
New messages like
```
Facet: 1 has zero surface area
```
must be messing with volume listing.
No
No
> convert-to-step.yml: fix for the new container

- scripts/material_map/geometry_epic.py
- scripts/material_map/run_material_map_validation.sh
This is an attempt to address https://github.com/eic/epic/actions/runs/12434661764/job/34719311689
No
No
> run_material_map_validation.sh: update to acts 34.1.0

- compact/far_backward/magnets.xml
The geometry of the Q3eR magnet was rotated but the field volume wasn't rotated to match.
No
No
> Add Q3eR field rotation

- .github/workflows/linux-eic-shell.yml
This PR changes another instance of /work/eic2 to /volatile/eic
> fix: /work/eic2 -> /volatile/eic

- src/ForwardRomanPot_geo.cpp
- src/PFRICH_geo.cpp
This PR removes some unplaced DetElements that appear to be used only for organizational purposes.
No.
No.
> fix: remove unplaced DetElement errors

- compact/hcal/backward.xml
- src/PolyhedraEndcapCalorimeter2_geo.cpp
> removed correcting tilt, rotation of assembly + automatically reflect

- .github/workflows/linux-eic-shell.yml
https://github.com/eic/epic/pull/859#discussion_r2076474913
Reverts eic/epic#856
> Revert "feat(ci): deploy capybara to pages"

- .github/workflows/linux-eic-shell.yml
This PR experiments with using a reusable workflow for (in this instance) list-open-prs. By placing this in a dedicate actions repository, it can be more easily reused across our repositories.
No.
No.
> feat(ci): use reusable workflow call for list-open-prs

- src/ForwardRomanPot_geo.cpp
This reverts RP change from #866 to fix https://github.com/eic/EICrecon/issues/1873.
> Partial revert: fix: avoid memory leaks in various geometry plugins

- .github/workflows/linux-eic-shell.yml
This PR ensures that the *.json and *.root files for the validate-material-map job will be uploaded correctly. See e.g. https://github.com/eic/epic/actions/runs/15736715539/job/44353322805 and artifact therein, which does not include root and json files.
No.
No.
> fix(ci): don't quote wildcards in upload-artifact

- scripts/material_map/readme.md
Create readme.md for material map
- [ x] Documentation update
- [ x] Documentation has been added / updated
> Create readme.md for material map

- scripts/test_ACTS.cxx
This PR fixes an issue with a CI script now that we have Acts 39.
No.
No.
> fix: don't ifdef on undefined preprocessor variable; assume Acts >= 37

- compact/calibrations.xml
Remove TaggerTrackerTransportation.onnx from calibrations, this has been superseded.
No
No
> Remove TaggerTrackerTransportation.onnx from calibrations
